### ISSUE TITLE
Support for new MPT models

### ISSUE THREAD

**Issue by canamika27** [h2oai/h2o-llmstudio#103]
Hi Team, Just wanted to check is there any plan for you guys to provide support for [MPT (MosaicML Pretrained Transformer)] base models such that we can finetune them with h2oai framework

**Comment by psinger** [comment]
I have started an experimental branch that fixes 1-2 tiny issues with that model:
https://github.com/h2oai/h2o-llmstudio/tree/psi/cfgoverwrite

But unfortunately I haven't had time yet to make it work with LORA, there is also an issue for it in peft:
https://github.com/huggingface/peft/issues/405

And finetuning without LORA also gives bad results

Would be amazing if someone could spend time investigating this.

**Comment by psinger** [comment]
MPT models work now, but need to be used with bs=1
