### ISSUE TITLE
[FEATURE] Extra setting for tokenizer model

### ISSUE THREAD

**Issue by psinger** [h2oai/h2o-llmstudio#108]
Sometimes one would want to use a different tokenizer compared to the backbone.

We can add an optional setting to specify a different tokenizer model.

**Comment by haqishen** [comment]
If one use a different tokenizer, the pretrained weight will be almost useless.
Does it make sense to you?

**Comment by psinger** [comment]
It can make sense for some use cases, but definitely not something common.
Will close it.
