### ISSUE TITLE
How to add llama model?

### ISSUE THREAD

**Issue by esokullu** [h2oai/h2o-llmstudio#112]
Importing llama checkpoints into h2o-llmstudio may not be possible due to the restrictions imposed by Meta. However, it would be helpful to have a guide or tutorial on how to import llama into h2o-llmstudio.

**Comment by pascal-pfeiffer** [comment]
You can already use them now, by entering the Hugging Face repo id to the `LLM Backbone` field. 
![image](https://github.com/h2oai/h2o-llmstudio/assets/1069138/0555234a-66c7-48b5-a539-2f274f5a91d8)
