### ISSUE TITLE
support for mpt-instruct model [FEATURE]

### ISSUE THREAD

**Issue by NarenZen** [h2oai/h2o-llmstudio#119]
### 🚀 Feature

Support for MPT-Instruct model
Hugging Face: mosaicml/mpt-7b-instruct

### Motivation

MPT-Instruct is the SOTA model and is commercially usable.
![Screenshot from 2023-05-19 10-14-49](https://github.com/h2oai/h2o-llmstudio/assets/78342459/7ee974ba-f552-4e60-a256-3373e91d8c33)

**Comment by pascal-pfeiffer** [comment]
Is there anything else that prevents you from using MPT other than: https://github.com/h2oai/h2o-llmstudio/issues/117 ?

**Comment by psinger** [comment]
Duplicate of https://github.com/h2oai/h2o-llmstudio/issues/103
