### ISSUE TITLE
Alpaca

### ISSUE THREAD

**Issue by esokullu** [h2oai/h2o-llmstudio#120]
Is it possible to finetune LLMs with datasets like Alpaca? When I try it is not accepted to import. Or maybe is there a tool to put alpaca format into oasst format?

**Comment by pascal-pfeiffer** [comment]
Hi @esokullu , thank you for your question. 

These lines for preparation of the dataset should help you understand what is needed to get it into the right format:
https://github.com/h2oai/h2o-llmstudio/blob/1935d84d9caafed3ee686ad2733eb02d2abfce57/app_utils/utils.py#LL1896C5-L1896C28


Bare minimum are two columns, question and answer as explained here: https://github.com/h2oai/h2o-llmstudio#data-format

You may also check out our data preparation notebook on kaggle: https://www.kaggle.com/code/philippsinger/openassistant-conversations-dataset-oasst1?scriptVersionId=127047926

**Comment by esokullu** [comment]
I understand. Thank you.
