### ISSUE TITLE
[CODE IMPROVEMENT] Base pip installs from model card on Pipfile or requirements.txt

### ISSUE THREAD

**Issue by pascal-pfeiffer** [h2oai/h2o-llmstudio#129]
### 🔧 Proposed code refactoring

The pip install requirements in the model card are currently hardcoded to

```
pip install transformers==4.28.1
pip install accelerate==0.18.0
pip install torch==2.0.0
```

We should base these on the actual used versions during training (Pipfile or requirements.txt)

### Motivation
Code maintainability

**Comment by maxjeblick** [comment]
Also, parsing `trust_remote_code` state from `cfg.yaml` and adding it to the model card examples would make sense (e.g. falcon models).

**Comment by pascal-pfeiffer** [comment]
> Also, parsing trust_remote_code state from cfg.yaml and adding it to the model card examples would make sense (e.g. falcon models).

Yes, would make sense. For the pipeline, we need to allow it anyway, but for the rest it would make sense to read it from the yaml and force the setting.
