### ISSUE TITLE
How to run it on AWS SAGEMAKER?

### ISSUE THREAD

**Issue by OnlinePage** [h2oai/h2o-llmstudio#133]
First of all, thanks to you guys for this tool.

 Can you guys tell us how we can run the gui version on cloud platforms like aws or azure . Most preferable **AWS SAGEMAKER.** For training large models we need obviously really good machines and they are most available by these services. 
For example: instance like g5.24 or others.

So any guide on running **GUI** on any out of the above cloud platforms?

**Comment by pascal-pfeiffer** [comment]
If you have SSH access to the machines, you can tunnel the port (10101) to your local machine and access the GUI this way. 
Would that already solve the issue?

Another option would be to use a reverse proxy such as ngrok
