### ISSUE TITLE
support for GPT4ALL-J, StableLM- Base and Falcon-40B-Instruct for fine tuning

### ISSUE THREAD

**Issue by OnlinePage** [h2oai/h2o-llmstudio#134]
Hi, can we train GPT4ALL-J,  StableLm models and Falcon-40B-Instruct  with the current llm studio?
 -->
Wouldn't be so nice 🙂

**Comment by pascal-pfeiffer** [comment]
What is blocking you?

**Comment by pascal-pfeiffer** [comment]
> and also for `tiiuae/falcon-7b` the error states ValueError: you need to enable allow_remote_code=True

Yes, this is expected. You need to switch on "Trust Remote Code" in the environment settings

<img width="304" alt="image" src="https://github.com/h2oai/h2o-llmstudio/assets/1069138/fc641a68-18b3-4ad3-8ed5-0b4815145bce">

**Comment by psinger** [comment]
`lmsys/fastchat-t5-3b-v1.0` is an encoder-decoder model which is currently not supported:
See https://github.com/h2oai/h2o-llmstudio/issues/100

falcon-7b works fine as @pascal-pfeiffer elaborated

**Comment by GabrieleMancone** [comment]
Where can i set trust_remote_code=True using llm_studio in google colab? Thanks in advance
