### ISSUE TITLE
[FEATURE] one click installers for windows and linux

### ISSUE THREAD

**Issue by risedangel** [h2oai/h2o-llmstudio#144]
### 🚀 Feature

one click installers for windows and linux

### Motivation

As a newbie in LLM's i prefer focusing on my LLM rather than focusing on installations. As of today I cant get the software to run on windows and i dont even know if that is possible.

**Comment by psinger** [comment]
We have docs for installing on Windows recommending WSL2: https://docs.h2o.ai/h2o-llmstudio/faqs#how-to-use-h2o-llm-studio-in-windows

Apart from that, we now support Docker to simplify setting it up. 

One click installers are not directly feasible for a product like LLM Studio, and the make commands are basically already enabling this.
