### ISSUE TITLE
Use LLMstudio for additional pretraining?

### ISSUE THREAD

**Issue by dcruiz01** [h2oai/h2o-llmstudio#146]
I would like to use llmstudio to provide an llm backbone model with additional pretraining on domain-specific documents. My understanding is the provided dataset must contain two columns (instruction and output). For additional pretraining on a model with a context length of 2048, would you recommend placing 2048 token chunks in the instruction column, and the corresponding 2049th token in the output column? Or would you set it up some other way?

Thank you for your help!

**Comment by dcruiz01** [comment]
Marking as closed and moving this over to the discussions section.

**Comment by tmm1** [comment]
moved to https://github.com/h2oai/h2o-llmstudio/discussions/148
