### ISSUE TITLE
[FEATURE] Allow adding custom tokens

### ISSUE THREAD

**Issue by Glavin001** [h2oai/h2o-llmstudio#151]
### 🚀 Feature

Ability to add arbitrary custom tokens, special or normal, via GUI to [tokenizer.add_tokens](https://huggingface.co/docs/transformers/internal/tokenization_utils#transformers.SpecialTokensMixin.add_tokens).

### Motivation

I want to add custom tokens to the tokenizer vocabulary.

Similar to the existing `Text Prompt Start` and `Text Answer Separator` tokens: https://github.com/h2oai/h2o-llmstudio/blob/529c5048d933c0b7a5911d667e4b696a92e3ad65/llm_studio/python_configs/text_causal_language_modeling_config.py#L40-L41

<img width="418" alt="image" src="https://github.com/h2oai/h2o-llmstudio/assets/1885333/5c516583-8eae-4d98-b4bd-5ed083220def">

Which can be explicitly added to the tokenizer with `Add Prompt Answer Tokens`.

**Comment by Glavin001** [comment]
I think the related code is here: https://github.com/h2oai/h2o-llmstudio/blob/529c5048d933c0b7a5911d667e4b696a92e3ad65/llm_studio/src/datasets/text_utils.py#L84-L92

I will try my best to make a Pull Request. Any advice is appreciated! I'm a notice at Python -- JavaScript/web dev by day.

**Comment by pascal-pfeiffer** [comment]
Closing as not planned as there don't seem to be a common use-case. If really needed, one could add the tokens manually upload to HF and use in H2O LLM Studio.
