### ISSUE TITLE
[FEATURE] Loss as metric

### ISSUE THREAD

**Issue by psinger** [h2oai/h2o-llmstudio#153]
### 🚀 Feature

Add a separate metric that calculates the loss only.

### Motivation

Generate can take a long time, but is needed for current metrics. 
Having a quick option with loss can be useful.

Issue is that validation insights cannot be generated in that case though.

**Comment by psinger** [comment]
Or maybe the best workaround is reducing the max inference length heavily? wdyt @pascal-pfeiffer

**Comment by pascal-pfeiffer** [comment]
I would be fine with adding it as a metric. Or perplexity
