### ISSUE TITLE
Improve Model Card Template

### ISSUE THREAD

**Issue by psinger** [h2oai/h2o-llmstudio#171]
Here are a few things to improve in the model card:

- Some models fail if input contains wrong keys, such as type ids. We should delete them after the tokenizer, or be specific of what we send to the `generate`, i.e. only send input ids and attention mask.
- Remove model validation section
- Potentially add quantization example everywhere

**Comment by Glavin001** [comment]
Applicable code: https://github.com/h2oai/h2o-llmstudio/blob/25164164fd36c5e9ac8ce39275a709e649516531/model_card_template.md

- [ ] Replace example prompt (i.e. `"Why is drinking water so healthy?"`, `How are you?`) with an actual example prompt from the dataset.

**Comment by psinger** [comment]
I think having a static example is a better idea here as it is hard to control and you might not want your data to leak outside.
