### ISSUE TITLE
[FEATURE] DeepSpeed in H2O-LLMStudio

### ISSUE THREAD

**Issue by binga** [h2oai/h2o-llmstudio#186]
### 🚀 Feature

Add DeepSpeed to h2o-llmstudio

### Motivation

Many reports say that DeepSpeed allows us to finetune LMMs on cheaper hardware - https://www.databricks.com/blog/2023/03/20/fine-tuning-large-language-models-hugging-face-and-deepspeed.html.

Any reason why h2o-llmstudio doesn't have it yet?

**Comment by binga** [comment]
Hi @psinger - let me share some background context. I'm trying to finetune the falcon 7b model using oasst dataset with 8  V100GPUs. if I'm able to do this, I will be able to use a proprietary dataset and finetune falcon 7b model for an internal usecase. However, I'm unable to finetune falcon on oasst due to an OOM error. So, I tried finetuning the EleutherAI/pythia-2.8B-deduped model and that didn't go through as well. I turned down the batch size to 1 and changed backbone dtype from float16 to bfloat16 but did not see success.

After multiple experiments, I was able to succesfully finetune EleutherAI/pythia-1b-deduped on 8 V100 GPUs. I'm suspicious if I'm doing something wrong as I believe with 8 V100 GPUs, we should be able to finetune bigger models.

To resolve this, I resorted to 2 solutions:
1. Use int8 as backbone dtype. I'm seeing an error which is tracked here - #185 
2. Use deepspeed or something similar to be able to scale training on the same infrastructure.

Am I missing something to scale my training?

**Comment by psinger** [comment]
@binga Do you have 16GB or 32GB V100?

And did you try `int4` already?

Usually int8 or int4 are the way to go. Seems like V100 are an issue there as tracked in the other issue.

**Comment by binga** [comment]
I am using 16GB V100 for now. Do you have a working hyperparameters set which is used for h2ogpt training?

**Comment by binga** [comment]
Great, thanks!

What was the hardware used for finetuning?

**Comment by psinger** [comment]
Mostly A100

**Comment by binga** [comment]
This helps, thanks @psinger. Let me try the following experiments and get back to this thread.
1. `int4` on V100 (32GB).
2. Both int8 and int4 on A10.

Appreciate the quick support :)

**Comment by psinger** [comment]
You can just paste the HF model name into the `backbone` field, the list is just a pre-defined list.

**Comment by binga** [comment]
That works. Thank you @psinger .

I'm finetuning the falcon models and it looks like I'm hitting the error tracked in #170 . I'll follow that issue. 

Closing this for now.
