### ISSUE TITLE
[CODE IMPROVEMENT] add update method to ConfigProblemBase

### ISSUE THREAD

**Issue by maxjeblick** [h2oai/h2o-llmstudio#190]
### 🔧 Proposed code refactoring

Add a function/method that is able to automatically update `ConfigProblemBase` and its corresponding sub config classes.
It should also be able to validate if a configuration has conflicting settings.

### Motivation

1. Ability to automatically change config items (visibility/values) based on current setting in the UI. As an example, when switching backbone, automatically populate lora target modules. Also, for RLHF some parameter should be hidden, such as _disabling lora_ or some generation settings.
2. Move config changes to a single class that can be called at beginning of training. Gives a unified view on how config is changed during training. One could also enforce to only use "correct" configurations when using command line.

**Comment by pascal-pfeiffer** [comment]
Great refactor idea, I like it a lot!

**Comment by pascal-pfeiffer** [comment]
could also be worth checking there: https://github.com/h2oai/h2o-llmstudio/issues/257

and maybe already at dataset import, too
