### ISSUE TITLE
[CODE IMPROVEMENT] Use GenerationConfig

### ISSUE THREAD

**Issue by psinger** [h2oai/h2o-llmstudio#206]
Our manual passing of parameters to `generate` is deprecated.

The new way to do this properly is to use:
https://huggingface.co/docs/transformers/main_classes/text_generation#transformers.GenerationConfig

We should set it accordingly, and also dump it with correct settings to the HF weights:
https://huggingface.co/h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v2/blob/main/generation_config.json

**Comment by shivance** [comment]
Hi @psinger, can I contribute to this?

**Comment by pascal-pfeiffer** [comment]
Hi @shivance, yes of course you are very welcome to contribute here

**Comment by psinger** [comment]
Let's also reset to default and remove do_sample and automatically set it if temperature is not 0

**Comment by psinger** [comment]
Closed via https://github.com/h2oai/h2o-llmstudio/pull/646
