### ISSUE TITLE
[FEATURE] Push a transformer model to Replicate

### ISSUE THREAD

**Issue by Glavin001** [h2oai/h2o-llmstudio#218]
### 🚀 Feature

See how: https://replicate.com/docs/guides/push-a-transformers-model

### Motivation

I want to host the fine-tuned large language model on a Replicate Serverless GPU instance.

**Comment by Glavin001** [comment]
I'm following the guide myself right now. It depends on Docker and in some cases (Runpod) we cannot use Docker-in-Docker, so LLM Studio would fail to push to Replicate in Runpod/etc.

**Comment by psinger** [comment]
@Glavin001 do you think this will be something very useful for the app or rather a very edge-case?

I believe it might be a bit out of scope and could be done post-hoc.

**Comment by Glavin001** [comment]
Yeah now that I've developed more with Replicate it feels like something people would want more customization/control over. At most, LLM Studio docs could link to some helpful resources for how to deploy to Huggingface, Replciate, Runpod, etc. However those implementation details could change depending on their needs. Gonna close this.
