### ISSUE TITLE
[FEATURE] Option to Quantize / GPTQ first then push to Huggingface

### ISSUE THREAD

**Issue by Glavin001** [h2oai/h2o-llmstudio#219]
### 🚀 Feature

See https://github.com/PanQiWei/AutoGPTQ/tree/main#quantization-and-inference

### Motivation

Much less VRAM & faster inference speeds.

**Comment by Glavin001** [comment]
Applicable code: https://github.com/h2oai/h2o-llmstudio/blob/25164164fd36c5e9ac8ce39275a709e649516531/app_utils/sections/experiment.py#L1776-L1811

**Comment by Glavin001** [comment]
I'm learning how to use AutoGPTQ now. I'd be up for contributing this!

**Comment by psinger** [comment]
Is there any benefit in pushing it directly quantized to HF vs. first pushing it in float16 and then quantizing?

**Comment by Glavin001** [comment]
I'd be +1 for pushing both, float16 then quantizing.

> Have a separate script that pulls float16 weights from HF, quantizes it, and pushes it separately quantized.

This is what I ended up doing. I was successful by copying most of [AutoGPTQ's Quick Tour](https://github.com/PanQiWei/AutoGPTQ#quantization-and-inference).

There's [a more advanced script](https://github.com/PanQiWei/AutoGPTQ/blob/main/examples/quantization/quant_with_alpaca.py) involving loading a dataset of examples before performing quantization, which I think would benefit from leveraging the dataset LLM Studio already has configured.

> Directly have a setting when pushing to push it quantized

I'd love to have pushing checkpoint to Huggingface simply include an optional toggle to quantize as well and push both.
Not sure if it should be 2 projects in Huggingface though? I'm new to Huggingface and 2 projects is what I've seen so far.

And then a few edits to the modal template for quantized version.

**Comment by psinger** [comment]
I think it is either two projects, or two branches.

But probably two projects is what people most of the times do.

Would be great feature to have this toggle.

**Comment by Glavin001** [comment]
Work in progress: https://github.com/h2oai/h2o-llmstudio/pull/285

**Comment by psinger** [comment]
AWQ is the new preferred quantization method, will explore if we can add it.

**Comment by psinger** [comment]
Closing in favor of https://github.com/h2oai/h2o-llmstudio/issues/374
