### ISSUE TITLE
[FEATURE] Separate functionality for system prompt training

### ISSUE THREAD

**Issue by psinger** [h2oai/h2o-llmstudio#223]
### 🚀 Feature

Add a separate setting to specify system prompt and corresponding system special token.

Such as
`<|system|>system prompt<|prompt|>prompt<|answer|>`

### Motivation

While prepending system prompt is currently supported, more flexible support might be useful.

**Comment by shivance** [comment]
Hi @psinger can I contribute to this?

**Comment by psinger** [comment]
@shivance thanks for volunteering, but I will take this one

please consider taking another open issue
