### ISSUE TITLE
[FEATURE] Add column for Backbone on 'View Experiments' screen

### ISSUE THREAD

**Issue by luizlf** [h2oai/h2o-llmstudio#228]
### 🚀 Feature

The 'View Experiments' screen starts to get a little confusing after you've run many experiments. The information displayed on it should help the user to find out quickly what they tried differently on a given run and to me it seems one such thing that is frequently changed is the experiment backbone, so it makes sense to add that information to the columns on 'View Experiments'.

**Comment by psinger** [comment]
Unofrtunately, there is only limited space in the table and fitting the backbone will not work.

A good suggestion is to name your experiments with the backbone included, so it will be easier for you to find them.

**Comment by psinger** [comment]
BTW: If you are running this locally, you can just add the code locally to make it show in the table.

**Comment by pascal-pfeiffer** [comment]
A more complex solution would be to allow customization of the table. Happy to take PRs for this.
