### ISSUE TITLE
[FEATURE] Option to view parent prompts on 'Validation Insights' and 'Sample Train Visualization'

### ISSUE THREAD

**Issue by luizlf** [h2oai/h2o-llmstudio#229]
### 🚀 Feature

For nested prompts (tree-like), H2O LLM Studio should have an option to display the parent conversations. Currently, on both 'Sample Train Visualization' (datasets tab) and 'Validation Insights' (for a completed experiment) it only shows the 'current' conversation (prompt+answer), without the proper context of previous interactions. For the user of LLM Studio it might be necessary to see such context to evaluate whether the conversation branch makes sense and/or the model gives good answers.

**Comment by psinger** [comment]
Thanks @luizlf for the issue.

Would you be able to contribute to this?
