### ISSUE TITLE
[BUG] Unable to Install LLM Studio

### ISSUE THREAD

**Issue by iamakalia** [h2oai/h2o-llmstudio#232]
### 🐛 Bug
Unable is getting an error while installing LLM studio

### To Reproduce
Comments from User:

```
got an error during the install.  Essentially, Apache Arrow installed because (in the virtual environment) cmake wasn't installed.  It was installed on the system (Pop_OS 22.04), but it wasn't installed in the virtual environment.  

I also tried Docker, but that failed as well.  The problem with Docker was that nVidia wasn't starting, and I (unfortunately) didn't know what nVidia process I needed to run before I tried to start the studio.
```
Attaching the error as well
[Error.txt](https://github.com/h2oai/h2o-llmstudio/files/11939764/Error.txt)

**Comment by maxjeblick** [comment]
This looks like a compatibility issue with Python 3.11, see [here](https://stackoverflow.com/questions/74254073/installation-error-streamlit-building-wheel-for-pyarrow-pyproject-toml-er).
Using a custom venv with Python 3.10, or using `make setup` (will create a pipenv enviroment automatically) should solve this.
