### ISSUE TITLE
[FEATURE] Add DPO optimization

### ISSUE THREAD

**Issue by maxjeblick** [h2oai/h2o-llmstudio#241]
### 🚀 Feature

Add direct preference optimization pipeline ([here](https://github.com/eric-mitchell/direct-preference-optimization)) as a new problem type.

### Motivation
From the paper: 
> DPO optimizes for human preferences while avoiding reinforcement learning.

**Comment by psinger** [comment]
Finished: https://github.com/h2oai/h2o-llmstudio/pull/530
