### ISSUE TITLE
[FEATURE] show the full conversation in the validation insights

### ISSUE THREAD

**Issue by pascal-pfeiffer** [h2oai/h2o-llmstudio#255]
### 🚀 Feature

Currently, only the last prompt + answer is shown in the validation insights. 
For better understanding, we should show the full conversation in case that `parent_id` is used.

**Comment by psinger** [comment]
Also add system prompt then

**Comment by psinger** [comment]
Duplicate of https://github.com/h2oai/h2o-llmstudio/issues/229 potentially?

**Comment by maxjeblick** [comment]
Fixed by #438
