### ISSUE TITLE
[FEATURE] Prevent infinite loop when selecting row id as "parent_id"

### ISSUE THREAD

**Issue by Surya-Murali** [h2oai/h2o-llmstudio#257]
_###_ 🐛 Bug

I am getting a Data Error while running an experiment on LLM Studio:

**ERROR: Data error occurred during H2O LLM Studio run**:
_Traceback (most recent call last):_
_File "/root/.local/share/virtualenvs/h2o_-_llmstudio_-_29knupLy/lib/python3.10/site_-_packages/torch/utils/data/dataloader.py", line 1133, in_ _try_get_data
data = self._data_queue.get(timeout=timeout)
File "/usr/lib/python3.10/queue.py", line 180, in get
self.not_empty.wait(remaining)_

The experiment runs for hours with no progress and eventually times out.

### To Reproduce

Use a dataset other than 'oasst' and merely run an experiment.
(I've shared my sample dataset via email)

**Comment by pascal-pfeiffer** [comment]
Error was due to an infinite loop caused by setting `parent_id` to the row id itself. 
Will rename the issue, so we can prevent this setting in future versions.
