### ISSUE TITLE
[DOC] Export model using command line 

### ISSUE THREAD

**Issue by whatvn** [h2oai/h2o-llmstudio#260]
### 📃 Documentation

To test some setting and create new experiment, llmstudio is good. But to run training from time to time, I think train.py and distributed_train is better. Do we have way to export model from output of train.py? 
### Motivation

I believe there's way to do that, as it can be done via UI. Export model using command line is real usecase and needed by many llmstudio's user.

**Comment by psinger** [comment]
The model weights will still be stored locally, so nothing is lost.

One functionality missing is a separate util that exports it to HF.
This feature request is already tracked here: https://github.com/h2oai/h2o-llmstudio/issues/95
