### ISSUE TITLE
[BUG] Clicking on Download logs/config button yields a 404

### ISSUE THREAD

**Issue by pligor** [h2oai/h2o-llmstudio#263]
### 🐛 Bug

Clicking on Download logs/config button yields a 404:

![Screenshot from 2023-07-07 23-56-37](https://github.com/h2oai/h2o-llmstudio/assets/1448173/cf2137cd-f4e3-4820-a440-57d3ed6cb2cf)

![Screenshot from 2023-07-07 23-55-25](https://github.com/h2oai/h2o-llmstudio/assets/1448173/fbf40ff1-f62b-4937-86e8-3773fc9a900f)

### To Reproduce

Note that the training was NOT finished. Does this play a role ?..

**Comment by pascal-pfeiffer** [comment]
Thank you for reporting. I am seeing the same on current main. 

#217 caused this issue with the full path for `data_folder` and `output_folder.

Need to look into a proper fix for the routing when others paths are used, too.

**Comment by Glavin001** [comment]
Sorry about that! Thanks for fixing
