### ISSUE TITLE
[DOC] ShareGPT Dataset Training docs

### ISSUE THREAD

**Issue by gururise** [h2oai/h2o-llmstudio#264]
### 📃 Documentation

Assuming it is possible to train on ShareGPT conversation dataset, I would like docs on how to do this.

### Motivation

ShareGPT conversation dataset is used in many fine-tuned models such as Vicuna, and has proven to be a good dataset for training chat-style models.  Looking at the current dataset [docs](https://github.com/h2oai/h2o-llmstudio#data-format), its not clear how one could take a [ShareGPT style dataset](https://huggingface.co/datasets/openchat/openchat_sharegpt4_dataset) and convert it to a format that will work in H2O LLM Studio.

**Comment by psinger** [comment]
Hello @gururise - could you please elaborate what is not clear to you exactly?

The data format required is very simple, it needs two columns provided in a csv or parquet file.
One column is the human input, and one column is the output of the bot.

You need to prepare your data in that format.
