### ISSUE TITLE
[FEATURE] Instruction on how to install in Windows

### ISSUE THREAD

**Issue by klauBertram** [h2oai/h2o-llmstudio#272]
### 🚀 Feature

Instruction on how to install in Windows box

### Motivation

Apologies, AI newbie here, be great if there are some instruction on how to run this in a windows box, thanks!

**Comment by pascal-pfeiffer** [comment]
The recommended way to use H2O LLM Studio on Windows OS is to use WSL 2.

https://docs.h2o.ai/h2o-llmstudio/faqs#how-to-use-h2o-llm-studio-in-windows

**Comment by psinger** [comment]
Please use as described WSL2. It is very easy to set-up and gives you all the Linux flexibility in Windows and it works well with CUDA. I am using it myself.

Otherwise there is also a duplicate issue: https://github.com/h2oai/h2o-llmstudio/issues/144
