### ISSUE TITLE
[CODE IMPROVEMENT] Creation of a python script to push the model to Hugging Face from CLI

### ISSUE THREAD

**Issue by diegomiranda02** [h2oai/h2o-llmstudio#279]
### 🔧 Proposed code refactoring

- Adaptation in the H2O code for publishing fine-tuned models from H2O LLM Studio to Hugging Face using the CLI

### Motivation

- Using the Google Colab or other web tools to run the fine-tuning process. This will be easier and practical to try the H2O LLM Studio.
- One more option to publish the model to Hugging Face. The only way to push the fine-tuned model to Hugging Face is from the graphic tool H2O LLM Studio using a local GPU or a cloud virtual machine with GPU as well.

P.S.: I have done some code adaptation following the patterns of the H2O LLM Studio code 
 Link https://github.com/diegomiranda02/cli_HF_h2o_llm_studio
In the section "The following code snippets were adapted using existing codes in the H2O LLM Studio project", steps 6 and 7. I hope the code can contribute to the project.

**Comment by pascal-pfeiffer** [comment]
Great work @diegomiranda02 thanks for linking your code.

Actually, we have this issue open for quite a while now (https://github.com/h2oai/h2o-llmstudio/issues/95) which describes exactly the pain points that you have and apparently solved already. Would you want to contribute this to H2O LLM Studio as integrated utility functions?

**Comment by diegomiranda02** [comment]
Sure @pascal-pfeiffer. Which steps should I take to do it?

**Comment by diegomiranda02** [comment]
@pascal-pfeiffer 

I have forked the repository and created the hugging_face_utils.py file inside the app_utils directory with two utility functions: publish_model_to_hugging_face and get_model_card.

Updated the experiment.py file and import the utility functions from the hugging_face_utils.py. Changed the method experiment_push_to_huggingface_dialog to directly call the publish_model_to_hugging_face utility function to use the same function using the CLI and the graphic tool. But I cannot test the graphic tool once I don´t have a GPU installed on my machine. Could you test it, please?

I have already tested the CLI to publish the model, which works properly. 

Link to the Hugging Face model published from CLI with the utility function 
https://huggingface.co/diegomiranda/testing-fork-model

**Comment by diegomiranda02** [comment]
The fork link https://github.com/diegomiranda02/h2o-llmstudio.git

**Comment by diegomiranda02** [comment]
> Great work @diegomiranda02 thanks for linking your code.
> 
> Actually, we have this issue open for quite a while now (#95) which describes exactly the pain points that you have and apparently solved already. Would you want to contribute this to H2O LLM Studio as integrated utility functions?

@pascal-pfeiffer The code is done.

**Comment by pascal-pfeiffer** [comment]
Thank you @diegomiranda02 , will you open a PR?

**Comment by diegomiranda02** [comment]
Hi @pascal-pfeiffer 

PR created https://github.com/h2oai/h2o-llmstudio/pull/300
