### ISSUE TITLE
[FEATURE] Add Open Llama 7B V2 to default model list

### ISSUE THREAD

**Issue by tmostak** [h2oai/h2o-llmstudio#282]
### 🚀 Feature

Now that there is a V2 of Open Llama 7B, it should either displace the V1 version of their 7B model, or be added as an additional option.

### Motivation

The new V2 version of Open Llama model now uses the original Llama tokenizer, plus seems to be trained on additional datasets, with performance surpassing the original V1 model according to their benchmarks.

See [here](https://huggingface.co/openlm-research/open_llama_7b_v2) for more.

**Comment by psinger** [comment]
I tried the v2 version the other day and it performed very poorly in fine-tuning in comparison to v1.

Not really sure what is the issue, everything looked fine from a technical stand-point.

Did you have any luck fine-tuning it?
I think I would prefer keeping the v1 version in the default list.

BTW: Just to make sure, you can always just paste any backbone into the field in the GUI, the default list is just a pre-selection.

**Comment by tmostak** [comment]
Hi @psinger, I just tested a full fine-tune using our text-to-SQL dataset of both the V1 and V2 7B Open Llama models, and received perplexity scores on the eval set of 1.127 for the V1 backbone and 1.116 for the V2 backbone (and in other iterations of training I've seen V2 perform better as well).

Not sure of the differences of your use case and training params but just offering one datapoint that V2 can be better or at least on par with V1.

And yes, I was aware that you could paste in any model path you wanted, just thought that it might be helpful for others to have easy access to the V2 model from the dropdown!

(While we're on the subject of model backbones, the new Salesforce XGen 8K model seems fairly promising and noteworthy as well and perhaps could be added).

**Comment by psinger** [comment]
Thanks @tmostak - I will recheck the v2, for now I will leave the v1 there.

I also like the xgen models, actually we also have a fine-tune there:
https://huggingface.co/h2oai/h2ogpt-gm-oasst1-en-xgen-7b-8k

I added your suggestions here:
https://github.com/h2oai/h2o-llmstudio/issues/238

Closing this issues.
