### ISSUE TITLE
Is there any documentation for detailed guidance of how to use the RLHF function with llm studio?[DOC]

### ISSUE THREAD

**Issue by zyzisastudyreallyhardguy** [h2oai/h2o-llmstudio#284]
### Motivation 

Is there any documentation for detailed guidance of how to use the RLHF function with llm studio?

**Comment by maxjeblick** [comment]
Thanks for opening this issue!
We are largely following the implementation of [trl](https://github.com/lvwerra/trl) library, which in turn is based upon"Fine-Tuning Language Models from Human Preferences" by D. Ziegler et al. [[paper](https://arxiv.org/pdf/1909.08593.pdf), [code](https://github.com/openai/lm-human-preferences)].

The recommended workflow is to enable RLHF and start with the default settings. There is some active discussion in [trl](https://github.com/lvwerra/trl) github issues on various parameters and how they affect the training results.
We will eventually also improve documentation on our side, in the meantime, feel free to ask any specific question here.

**Comment by psinger** [comment]
deprecated
