### ISSUE TITLE
I am using the local chatglm-6b model and the following error occurs

### ISSUE THREAD

**Issue by smileyee** [h2oai/h2o-llmstudio#286]
### 🐛 Bug
I am using the local chatglm-6b model and the following error occurs, is it not currently supported?
 
raise ValueError(
ValueError: Unrecognized configuration class for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextC
onfig, ElectraConfig, ErnieConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MvpConfig, OpenLlamaConfig
, OpenAIGPTConfig, OPTConfig, PegasusConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, TransfoXLConfig, TrOCR
Config, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.

**Comment by maxjeblick** [comment]
Thanks for opening this issue! 
`THUDM/chatglm-6b` model is not following the canonical interface of `AutoModelForCausalLM`  which H2O LLM Studio relies on (see e.g [h2ogpt-gm-oasst1-en-2048-falcon-7b-v3](https://huggingface.co/h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3) model card). In their example code, they are using 

```
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().cuda()  # this should be AutoModelForCausalLM class 
response, history = model.chat(tokenizer, "你好", history=[])  # there is no .chat method for other models, they use .generate
```
where I indicated the differences w.r.t. standardized code.
