### ISSUE TITLE
[BUG] Chatbot card broken for llama v2

### ISSUE THREAD

**Issue by maxjeblick** [h2oai/h2o-llmstudio#295]
### 🐛 Bug
Hugginface token is not set when loading the model in the app.
Thus, chat for llama v2 models (and probably other private models) fails with

`requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/meta-llama/Llama-2-7b-chat-hf/resolve/main/tokenizer_config.json`

**Comment by maxjeblick** [comment]
Probably also affect model download

**Comment by pascal-pfeiffer** [comment]
It should be set with `HUGGINGFACE_TOKEN` env var. But I agree, that is not ideal. We should probably rewrite it.

**Comment by pascal-pfeiffer** [comment]
(create_nlp_backbone doesn't have access to `q`)

**Comment by maxjeblick** [comment]
Still don't get why `from_pretrained` doesn't go to local files then, but ok

**Comment by pascal-pfeiffer** [comment]
My guess would be that it checks the checksums first before using the cache.
