### ISSUE TITLE
[BUG] FileNotFoundError

### ISSUE THREAD

**Issue by dsauce** [h2oai/h2o-llmstudio#302]
### 🐛 Bug

Create experiments sections says "something went wrong". Error report from LLM Studio is below.

### To Reproduce

q.app

script_sources: ['/_f/f2c95323-c429-4fb7-96ad-67e39b51a8dc/tmptsfiit6e.min.js']
initialized: True
wave_utils_stack_trace_str: ### stacktrace
Traceback (most recent call last):

  File "/workspace/./app_utils/handlers.py", line 190, in handle
    await experiment_start(q)

  File "/workspace/./app_utils/sections/experiment.py", line 452, in experiment_start
    option_items = get_ui_elements(cfg=q.client["experiment/start/cfg"], q=q)

  File "/workspace/./app_utils/utils.py", line 1075, in get_ui_elements
    elements_group = get_ui_elements(cfg=v, q=q, limit=limit, pre=pre)

  File "/workspace/./app_utils/utils.py", line 1015, in get_ui_elements
    poss_values, v = cfg._get_possible_values(

  File "/workspace/./llm_studio/python_configs/base.py", line 81, in _get_possible_values
    dataset, value = dataset_fn(field, value)

  File "/workspace/./app_utils/utils.py", line 617, in get_dataset
    dataset_cfg = load_config_yaml(dataset["config_file"]).dataset.__dict__

  File "/workspace/./llm_studio/src/utils/config_utils.py", line 208, in load_config_yaml
    with open(path, "r") as fp:

FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/Desktop/chatIBD/h2o_llm_studio/h2o-llmstudio/data/user/oasst/text_causal_language_modeling_config.yaml'

q.user

q.client

app_db: <app_utils.db.Database object at 0x7ff0ef4bba00>
client_initialized: True
mode_curr: error
theme_dark: True
default_aws_bucket_name: bucket_name
default_kaggle_username: 
set_max_epochs: 50
set_max_batch_size: 256
set_max_gradient_clip: 10
set_max_lora_r: 256
set_max_lora_alpha: 256
gpu_used_for_chat: 1
default_number_of_workers: 8
default_logger: None
default_neptune_project: 
default_openai_azure: False
default_openai_api_base: https://example-endpoint.openai.azure.com
default_openai_api_deployment_id: deployment-name
default_openai_api_version: 2023-05-15
default_gpt_eval_max: 100
default_safe_serialization: True
delete_dialogs: True
chart_plot_max_points: 1000
init_interface: True
notification_bar: None
nav/active: experiment/start
experiment/list/mode: train
dataset/list/df_datasets: Empty DataFrame
Columns: [id, name, path, config_file]
Index: []
experiment/list/df_experiments: Empty DataFrame
Columns: [id, name, mode, dataset, config_file, path, seed, process_id, gpu_list, status, info]
Index: []
expander: True
dataset/list: False
dataset/list/table: []
experiment/list: True
experiment/list/table: []
experiment/start: True
experiment/start/cfg_category: text
experiment/start/cfg_file: text_causal_language_modeling_config
experiment/start/cfg_experiment_prev: None
experiment/start/cfg_file_prev: text_causal_language_modeling_config
experiment/start/prev_dataset: None
experiment/start/cfg_sub: 
experiment/start/dataset: 1
experiment/start/cfg_mode/mode: train
experiment/start/cfg_mode/from_dataset: True
experiment/start/cfg_mode/from_cfg: True
experiment/start/cfg_mode/from_default: True
experiment/start/cfg_mode/from_dataset_args: False
experiment/start/cfg: ConfigProblemBase(output_directory='output/text_causal_language_modeling_config', experiment_name='granite-shrimp', _parent_experiment='', llm_backbone='EleutherAI/pythia-2.8b-deduped', dataset=ConfigNLPCausalLMDataset(dataset_class=<class 'llm_studio.src.datasets.text_causal_language_modeling_ds.CustomDataset'>, personalize=False, chatbot_name='h2oGPT', chatbot_author='H2O.ai', train_dataframe='/path/to/train.csv', validation_strategy='automatic', validation_dataframe='', validation_size=0.01, data_sample=1.0, data_sample_choice=('Train', 'Validation'), system_column='None', prompt_column=('instruction', 'input'), answer_column='output', parent_id_column='None', text_system_start='<|system|>', text_prompt_start='<|prompt|>', text_answer_separator='<|answer|>', limit_chained_samples=False, add_eos_token_to_system=True, add_eos_token_to_prompt=True, add_eos_token_to_answer=True, mask_prompt_labels=True, _allowed_file_extensions=('csv', 'pq', 'parquet')), tokenizer=ConfigNLPCausalLMTokenizer(max_length_prompt=256, max_length_answer=256, max_length=512, add_prompt_answer_tokens=False, padding_quantile=1.0, use_fast=True, add_prefix_space=False), architecture=ConfigNLPCausalLMArchitecture(model_class=<class 'llm_studio.src.models.text_causal_language_modeling_model.Model'>, reward_model_class=<class 'llm_studio.src.models.text_reward_model.RewardModel'>, pretrained=True, backbone_dtype='float16', gradient_checkpointing=True, force_embedding_gradients=False, intermediate_dropout=0, pretrained_weights=''), training=ConfigNLPCausalLMTraining(loss_class=<class 'llm_studio.src.losses.text_causal_language_modeling_losses.Losses'>, loss_function='TokenAveragedCrossEntropy', optimizer='AdamW', learning_rate=0.0001, differential_learning_rate_layers=(), differential_learning_rate=1e-05, batch_size=2, drop_last_batch=True, epochs=1, schedule='Cosine', warmup_epochs=0.0, weight_decay=0.0, gradient_clip=0.0, grad_accumulation=1, lora=True, lora_r=4, lora_alpha=16, lora_dropout=0.05, lora_target_modules='', save_best_checkpoint=False, evaluation_epochs=1.0, evaluate_before_training=False, train_validation_data=False, use_rlhf=False, reward_model='OpenAssistant/reward-model-deberta-v3-large-v2', adaptive_kl_control=True, initial_kl_coefficient=0.2, kl_target=6.0, kl_horizon=10000, advantages_gamma=0.99, advantages_lambda=0.95, ppo_clip_policy=0.2, ppo_clip_value=0.2, scaling_factor_value_loss=0.1, ppo_epochs=4, ppo_batch_size=1, ppo_generate_temperature=1.0, offload_reward_model=False), augmentation=ConfigNLPAugmentation(nlp_augmentations_class=<class 'llm_studio.src.augmentations.nlp_aug.BaseNLPAug'>, token_mask_probability=0, skip_parent_probability=0, random_parent_probability=0), prediction=ConfigNLPCausalLMPrediction(metric_class=<class 'llm_studio.src.metrics.text_causal_language_modeling_metrics.Metrics'>, metric='GPT', metric_gpt_model='gpt-3.5-turbo-0301', min_length_inference=2, max_length_inference=256, batch_size_inference=0, do_sample=False, num_beams=1, temperature=0.3, repetition_penalty=1.2, stop_tokens='', top_k=0, top_p=1.0, num_history=4), environment=ConfigNLPCausalLMEnvironment(gpus=('0',), mixed_precision=True, compile_model=False, use_fsdp=False, find_unused_parameters=False, trust_remote_code=True, huggingface_branch='main', number_of_workers=4, seed=-1, _seed=0, _distributed=False, _distributed_inference=True, _local_rank=0, _world_size=1, _curr_step=0, _curr_val_step=0, _rank=0, _device='cuda', _cpu_comm=None), logging=ConfigNLPCausalLMLogging(logger='None', neptune_project='', _neptune_debug=False, plots_class=<class 'llm_studio.src.plots.text_causal_language_modeling_plots.Plots'>, number_of_texts=10, _logger=None))
experiment/start/dataset_prev: 1
experiment/start/cfg/output_directory: output/text_causal_language_modeling_config
experiment/start/cfg/experiment_name: granite-shrimp
experiment/start/trigger_ks: ['train_dataframe', 'system_column', 'validation_strategy', 'parent_id_column', 'personalize', 'data_sample']
experiment/start/cfg/_parent_experiment: 
experiment/start/cfg/llm_backbone: EleutherAI/pythia-2.8b-deduped
experiment/start/cfg/dataset: ConfigNLPCausalLMDataset(dataset_class=<class 'llm_studio.src.datasets.text_causal_language_modeling_ds.CustomDataset'>, personalize=False, chatbot_name='h2oGPT', chatbot_author='H2O.ai', train_dataframe='/path/to/train.csv', validation_strategy='automatic', validation_dataframe='', validation_size=0.01, data_sample=1.0, data_sample_choice=('Train', 'Validation'), system_column='None', prompt_column=('instruction', 'input'), answer_column='output', parent_id_column='None', text_system_start='<|system|>', text_prompt_start='<|prompt|>', text_answer_separator='<|answer|>', limit_chained_samples=False, add_eos_token_to_system=True, add_eos_token_to_prompt=True, add_eos_token_to_answer=True, mask_prompt_labels=True, _allowed_file_extensions=('csv', 'pq', 'parquet'))
experiment/start/cfg/dataset_class: <class 'llm_studio.src.datasets.text_causal_language_modeling_ds.CustomDataset'>
experiment/start/cfg/personalize: False
experiment/start/cfg/chatbot_name: h2oGPT
experiment/start/cfg/chatbot_author: H2O.ai
home: False
report_error: True
dataset/import: True
dataset/list/delete: False
dataset/import/source: Upload
dataset/import/id: None
dataset/import/cfg_file: None
experiment/list/refresh: False
experiment/list/compare: False
experiment/list/stop: False
experiment/list/delete: False
experiment/stop: True
experiment/list/current/noreset: False

q.events

q.args

report_error: True

stacktrace

Traceback (most recent call last):

File “/workspace/./app_utils/handlers.py”, line 190, in handle await experiment_start(q)

File “/workspace/./app_utils/sections/experiment.py”, line 452, in experiment_start option_items = get_ui_elements(cfg=q.client[“experiment/start/cfg”], q=q)

File “/workspace/./app_utils/utils.py”, line 1075, in get_ui_elements elements_group = get_ui_elements(cfg=v, q=q, limit=limit, pre=pre)

File “/workspace/./app_utils/utils.py”, line 1015, in get_ui_elements poss_values, v = cfg._get_possible_values(

File “/workspace/./llm_studio/python_configs/base.py”, line 81, in _get_possible_values dataset, value = dataset_fn(field, value)

File “/workspace/./app_utils/utils.py”, line 617, in get_dataset dataset_cfg = load_config_yaml(dataset[“config_file”]).dataset.dict

File “/workspace/./llm_studio/src/utils/config_utils.py”, line 208, in load_config_yaml with open(path, “r”) as fp:

FileNotFoundError: [Errno 2] No such file or directory: ‘/home/ubuntu/Desktop/chatIBD/h2o_llm_studio/h2o-llmstudio/data/user/oasst/text_causal_language_modeling_config.yaml’
Error

**Comment by maxjeblick** [comment]
Thanks for opening this issue!
From the logs, it looks as if the bug you encounter is the same as https://github.com/h2oai/h2o-llmstudio/issues/258 which was resolved last week.

To resolve this issue, you can
- checkout the latest commit of LLM Studio
- in case you don't have uploaded any other dataset, delete the `data/` folder and restart the app. That will retrigger the creating of the OASST dataset. Alternatively, you can also run `prepare_default_dataset`, which will create the OASST .pq files, zip them and upload them within the UI.

Please come back if you have more questions, or if the issue still exists.
