### ISSUE TITLE
[FEATURE] more backend repo support - advice 

### ISSUE THREAD

**Issue by ivlovric** [h2oai/h2o-llmstudio#307]
### 🚀 
Along with huggingface checkpoint model export support, I was wondering what kind of similar model export backend support could be beneficial, something like ML Flow and Artifactory support would benefit my environment for example but would like some suggestions from you/dev side what path here is appropriate to go along after which we will contribute in that regard with some meaningful PR.

### Motivation

Main motivation is better integration with more model registry backends that are local to some environments and not public like huggingface

Thanks,
Ivica

**Comment by maxjeblick** [comment]
Thanks for opening this issue, Ivaca. Currently, we do not actively plan to commit to additional model export formats. With the standardized Huggingface format, users are flexible on how to further deploy the model - there is a lot of variety and different ways of model optimizations atm, such as https://github.com/huggingface/text-generation-inference.

If you find a particular model format  helpful for inference, feel free to link it here, we are open to contributions :)

See also https://github.com/h2oai/h2o-llmstudio/issues/219
