### ISSUE TITLE
[BUG] PermissionError: [Errno 13] Permission denied: '/workspace/data/user'

### ISSUE THREAD

**Issue by gpnath82** [h2oai/h2o-llmstudio#313]
### 🐛 Bug

Traceback (most recent call last):
  File "/home/llmstudio/.local/share/virtualenvs/workspace-dqq3IVyd/lib/python3.10/site-packages/h2o_wave/server.py", line 374, in _process
    await self._handle(q)
  File "/workspace/./app.py", line 39, in serve
    await initialize_client(q)
  File "/workspace/./app_utils/initializers.py", line 84, in initialize_client
    os.makedirs(get_data_dir(q), exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/workspace/data/user'

I have modified docker file as below

RUN adduser --uid 1999 llmstudio
RUN mkdir /workspace
RUN chown llmstudio -R /workspace
USER llmstudio
WORKDIR /workspace

**Comment by gpnath82** [comment]
Hi @maxjeblick Yes I just gitclone last week

**Comment by pascal-pfeiffer** [comment]
It would be important if this commit is included in your pull: https://github.com/h2oai/h2o-llmstudio/commit/b39b02939c3201336b2c86431d6ca4b787311dde

It was merged last week.

Could you please check and maybe retest that?

**Comment by gpnath82** [comment]
@pascal-pfeiffer Sorry I didn't update, this issue is resolved now

**Comment by micsthepick** [comment]
looks like the latest main has the same issue again?
