### ISSUE TITLE
[FEATURE] Add parsers to train on additional text file formats

### ISSUE THREAD

**Issue by ericchu0** [h2oai/h2o-llmstudio#315]
### 🚀 Feature

On the Import Dataset screen, we should be able to upload more file formats (starting with txt, markdown, pdf, docx, doc, and json) and have the dataset converted into the training-compatible format that is used by LLM Studio.

h2oGPT already supports upload of multiple file formats (pdf, txt, css, tool, py, rust, rtf, md, html, enex, elm, ePub, dot, pptx, ppt, zip, urls, png, jpg, jpeg) using langchain (https://github.com/h2oai/h2ogpt/blob/main/src/gpt_langchain.py). The work there can be leveraged in LLM Studio to chunk text from other file formats to a single column table or csv file for LLM studio training.

### Motivation

Text commonly exists in multiple file formats beyond csv and pq. We can adapt existing parsing functionality from h2oGPT to LLM Studio.

**Comment by psinger** [comment]
Hi @ericchu0 -

there is a difference between training and inference formats. In h2ogpt the main goal is to allow uploading documents and then ask questions about these documents in an inference setting.

Here, the goal is to train models on an input/output format. Automatically generating such training data from arbitrary types of documents is out-of-scope of this project as this depends heavily on your use case and will be hard to generalize.

We also have another repository which allows to automatically generate input/output for documents:
https://github.com/h2oai/h2o-wizardlm

I suggest following this procedure and then importing in H2O LLM Studio for training.
