### ISSUE TITLE
[FEATURE] finetune llama2-13b-chat-hf on custom data set

### ISSUE THREAD

**Issue by llmwesee** [h2oai/h2o-llmstudio#326]
How we can finetune llama2 chaf hf models using llm studio on our custom data set. for data formatting step  can we use same method that are used in sample dataset provided by llm studio. and what are the hyper parameters & evaluation metric we should consider especially with llama2 which should improve the performance

Please outline the detailed instruction with step by step guide using both script and llmstudio UI

**Comment by llmwesee** [comment]
what kind of prompt(plain, human-bot or custom or any other). we should consider and how can we use RoPe in finetuning. I have downloaded llama2 using h2ochatgpt and it saved in my local .cache in hf then we should re download it for llmstudio or it take it from there.

**Comment by psinger** [comment]
We currently dont explicitly support RoPe, but you can use any long-context model from HF out of the box.

You can just paste the cache folder into the llm backbone field.

For more general questions, please consult the README, docs, or ask in our community discord.
https://docs.h2o.ai/h2o-llmstudio/
