### ISSUE TITLE
[BUG] OOM errors during fine-tuning with Polyglot 12.8B models

### ISSUE THREAD

**Issue by yum-yeom** [h2oai/h2o-llmstudio#330]
### 🐛 Bug

hello. I'm trying to train Polyglot 12.8B model using h2o llm-studio, but I'm getting an OOM error.

The GPU I am using is Nvidia A5000 24GB 4 sheets, and the params I used are as follows zip file. 

- Using GPU 
![image](https://github.com/h2oai/h2o-llmstudio/assets/51901261/1ed080ec-685f-4ce1-b9de-1b553a8eaa46)
- config & logs
[Uploading logs_polyglot-ko-12.8b_12.8b_koalpaca-v1.1a-row21155_v3_bs1_gas8.zip…]()

Is there any solution?

**Comment by pascal-pfeiffer** [comment]
There are multiple ways to bring down memory consumption. 
Mainly:
- int4 training
- smaller batchsize
- lower token length for question and answer

There is also an ongoing effort to split the model weights across multiple GPUs during training in this PR: https://github.com/h2oai/h2o-llmstudio/pull/288
