### ISSUE TITLE
[CODE IMPROVEMENT] Import dataset from Hugging Face

### ISSUE THREAD

**Issue by pascal-pfeiffer** [h2oai/h2o-llmstudio#335]
### 🔧 Proposed code refactoring

Allow simple import of dataset from Hugging Face

```python
from datasets import load_dataset
import pandas as pd

Load your dataset
dataset = load_dataset('fka/awesome-chatgpt-prompts')  # replace with the name of your desired dataset

 Convert to pandas DataFrame
df = pd.DataFrame(dataset['train'])

 Save DataFrame to csv
df.to_csv('my_dataset.csv', index=False)
```

### Motivation

Raised by Maher on Discord (https://discord.com/channels/1097462770674438174/1100718594809147402/1136414136495001680)

**Comment by pritthakkar** [comment]
@pascal-pfeiffer I would like to work on this issue, can you please give me more details that what exact changes i have to make ?
