### ISSUE TITLE
[QUESTION] The train DataFrame does not contain the required column: output.

### ISSUE THREAD

**Issue by avemio-digital** [h2oai/h2o-llmstudio#336]
### 🐛 Bug

For custom csv file , its generates above error whenever I tried to execute h20llmstudiocli version.

### To Reproduce
system: colab

**Comment by pascal-pfeiffer** [comment]
If you haven't specified anything else, `output` is the default column name for the "answer" field. 

```yaml
dataset:
    answer_column: output
```

Your dataset apparently doesn't have this column, so it fails.

**Comment by sooraj007** [comment]
@psinger @pascal-pfeiffer this issue happened me to also 
when i debug it  prompt_column=('instruction',), answer_column='output\r'  its automatically adding that /r to the output, i checked my csv column name is output and training time when we select it seems correct but athe experiment time i tried to inspect ui in the dropdown when opening output it shows space after r 
so please fix this issue

**Comment by psinger** [comment]
Solved, as the error only persists due to wrong setting as explained by @pascal-pfeiffer
