### ISSUE TITLE
[DOC] Add back information how to continue pretraining (only one data col)

### ISSUE THREAD

**Issue by pascal-pfeiffer** [h2oai/h2o-llmstudio#340]
### 📃 Documentation

We had this in our README and it is missing from documentation:

--------------

❓ What if my data is not in question and answer form, I just have documents? How can I fine-tune the LLM model?

To train a chatbot style model, you need to convert your data into a question and answer format.

If you really want to continue pretraining on your own data without teaching a question answering style, prepare a dataset with all your data in a single column Dataframe. Make sure that the length of the text in each row is not too long. In the experiment setup, remove all additional tokens (e.g. `<|prompt|>`, `<|answer|>`, for `Text Prompt Start` and `Text Answer Start` respectively) and disable `Add Eos Token To Prompt` and `Add Eos Token To Answer`. Deselect everything in the `Prompt Column`.

**Comment by sherenem** [comment]
Resolved with https://github.com/h2oai/h2o-llmstudio/pull/388

Should H2O LLM Data Studio also be a part of the answer for this FAQ to help users to get their data into Q&A format? Or should we not add this in here just yet? 

CC: @pascal-pfeiffer @shivam5992

**Comment by pascal-pfeiffer** [comment]
H2O LLM Data Studio is not part of this repository and not open source. We can add a generic notice about Enterprise solutions from [H2O.ai](http://h2o.ai/) and a link to [this blogpost](https://blog.h2o.ai/blog/streamlining-data-preparation-for-fine-tuning-of-large-language-models/).
