### ISSUE TITLE
[QUESTION] OOM Error Nvidia RTX 3060 12GB

### ISSUE THREAD

**Issue by JarcauCristian** [h2oai/h2o-llmstudio#343]
### 🐛 Bug

Hello again!
    I am trying to train a model on a NVIDIA RTX 3060 with 12GB with the default settings on the  
experiment, and at first the backbone model loads just fine, but after all the checkpoint shards are loaded the experiment failed and I get OOM error. Can you please tell me what are the minimum requirements for the GPU, because I have run experiments on a Google Colab with a Tesla T4 with 15GB and it works just fine. Or maybe if is something that I need to configure elsewhere in order to be able to run an  experiment.
Thank you in advance!

**Comment by psinger** [comment]
Try changing the dtype to int4 and reduce the batch size.

**Comment by JarcauCristian** [comment]
It works now. Thank you very much, and sorry for bothering you.
