### ISSUE TITLE
[FEATURE] Add rerun existing experiment

### ISSUE THREAD

**Issue by sooraj007** [h2oai/h2o-llmstudio#347]
### 🚀 Feature

I am not finding to rerun the failed experimentm is there any option to rerun.

### Motivation

If i already selected everything and train failed i need to start from beginning.

**Comment by pascal-pfeiffer** [comment]
Hi @sooraj007 , you can click on the 3-dot menu from an existing experiment and then "New experiment" to start a new experiment using the same parameters.

**Comment by psinger** [comment]
Hi @sooraj007 -

this functionality already exists:
- click on the kebab menu on the right
- click on New Experiment
- This will re-use the same settings and you can run the experiment

![image](https://github.com/h2oai/h2o-llmstudio/assets/1677826/c231856a-c821-48e3-9345-b2a61bb3aac8)
