### ISSUE TITLE
Tokenizer class LlamaTokenizer does not exist or is not currently imported

### ISSUE THREAD

**Issue by FarhanAnis005** [h2oai/h2o-llmstudio#358]
hey i am trying to use TheBloke/Llama-2-7b-chat-fp16 instead of EleutherAI/pythia-2.8b-deduped but is showing this ValueError: Tokenizer class LlamaTokenizer does not exist or is not currently imported.  please somebody help

**Comment by psinger** [comment]
Llama-2 works fine.

You are probably on a real old transformer version.

Did you make sure to follow the guidelines in README and also run `make setup`?

**Comment by psinger** [comment]
if you share your notebook maybe someone could help

**Comment by arkodeep3404** [comment]
> if you share your notebook maybe someone could help

hello I'm arkodeep l. I'm working on the same project with farhan. 

we are using the same notebook given in the official readme. we have just changed the dataset and the model. 

i did some digging and I think that by default when the virtual environment is being created at the beginning with the "!make setup > /dev/null" command, the dependencies required for the EleutherAI/pythia-2.8b-deduped model are being downloaded. and after that when I try to change the model to TheBloke/Llama-2-7b-chat-fp16 it is giving the error. 

i tried experimenting with the Llama model on another notebook without a virtual environment and it works fine. so I think it is the problem with the virtual environment. 

here is the exact error for your reference:

File "/kaggle/working/cfg_notebook.py", line 3, in <module>
    tokenizer = AutoTokenizer.from_pretrained('TheBloke/Llama-2-7b-chat-fp16')
  File "/root/.local/share/virtualenvs/working-MLRu3Pvq/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 676, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class LlamaTokenizer does not exist or is not currently imported.

the tokenizer can be correctly loaded in the base environment but when it works in the virtual environment it causes the error.

**Comment by psinger** [comment]
Ah okay, I know why.

In this notebook it is using a very old version of LLM Studio with a fixed git checkpoint:
`!cd h2o-llmstudio && git checkout ce10af57ff118a2bbb81b5b3eae12273e290299a -q`

You would need to pull the most recent LLM Studio there and adjust accordingly.
