### ISSUE TITLE
[CODE IMPROVEMENT] Refactor chained samples

### ISSUE THREAD

**Issue by maxjeblick** [h2oai/h2o-llmstudio#370]
### 🔧 Proposed code refactoring

Extract logic for computing conversation chains into  separate functions/helper class.

### Motivation

Currently, it is not possible to easily extract complete conversations without initializing the `CustomDataset` class.
The dataset class introduces some side effects (e.g. it automatically adds eos token to system text) and only shows complete samples if `cfg.dataset.limit_chained_samples` is True.

Useful for subsequent tasks such as:
- #337
- #229
- Also better to test in isolation

**Comment by pascal-pfeiffer** [comment]
Maybe consider to refactor in a way that the Llama2-chat prompting style can be used in it's precise form where the sys prompt is not prepended but rather included in the first instruction
