### ISSUE TITLE
How to sign into LLM Data studio

### ISSUE THREAD

**Issue by Shantan243** [h2oai/h2o-llmstudio#379]
Hi,

I have tried signing up LLM studio by giving forgot password/unlock account with 2 emails ids primary and secondary. I do not see reset mail link nor a sign up processs is given clearly.

Please share and guide a step by step process of signing up LLM studio. Thanks alot!

**Comment by psinger** [comment]
Hi @Shantan243 - could you please elaborate a bit more?

This repository is for LLM Studio and there is no login required.
