### ISSUE TITLE
[FEATURE] Adjust the priority of experiments in the queue

### ISSUE THREAD

**Issue by haqishen** [h2oai/h2o-llmstudio#387]
### 🚀 Feature

When I have several experiments in the queue, I hope to change the priority of a particular experiment in the queue to achieve a 'jump the queue' effect.

### Motivation

For example, I currently have 3 experiments in the queue. I want to bring the last experiment to the front. The current approach is to delete the first two experiments and then re-add them to the queue.

<img width="1226" alt="image" src="https://github.com/h2oai/h2o-llmstudio/assets/10557602/a5febe2b-0606-40f6-94e9-35175e0ec2bf">

If I have many experiments in my queue, this operation is very tedious. Therefore, I want to use a simpler method to adjust the priority of experiments in the queue.

**Comment by psinger** [comment]
@haqishen this is unfortunately quite complicated to implement, so not sure we will try to add it anytime soon.
