### ISSUE TITLE
[FEATURE]Finetune LLama-2-70B using 16 * A10 GPUs.

### ISSUE THREAD

**Issue by babytdream** [h2oai/h2o-llmstudio#390]
Hello!Can I use LLM Studio to Finetune LLama-2-70B using 16 * A10 (16 * 24G)GPUs ?
Can you give me a command if possible？Thanks!

**Comment by psinger** [comment]
We currently do not directly support multi-node. I assume this is a multi-node setup, right?

**Comment by babytdream** [comment]
@psinger Yes, it is. Can I finetune it in FSDP + 16-bit LoRA , FSDP + 8-bit qLoRA or FSDP or 4-bit qLoRA.

**Comment by psinger** [comment]
FSDP deepspeed support is currently ongoing work: https://github.com/h2oai/h2o-llmstudio/pull/288

And relevant open issues:
https://github.com/h2oai/h2o-llmstudio/issues/98
https://github.com/h2oai/h2o-llmstudio/issues/239

Multi-node is currently not on the roadmap.

**Comment by pascal-pfeiffer** [comment]
Actually, multi node should be possible with CLI (as using native torchrun), but I never tried myself.
