### ISSUE TITLE
[FEATURE] API's extension - Cohere and Azure OpenAI 

### ISSUE THREAD

**Issue by micuentadecasa** [h2oai/h2o-llmstudio#393]
### 🚀 Feature

I would love to use Azure OpenAI instead of GPT4, or using Cohere API.

### Motivation

I have an Azure OpenAI subscription for the company and I need to use this instead of using the GPT4 OpenAI API. In addition I have also a Cohere account.

Adding more possibilities will extend the adoption of this tool.

Regards.

**Comment by pascal-pfeiffer** [comment]
Azure OpenAI is already supported. Please visit the settings page and set these according to your installation:
![image](https://github.com/h2oai/h2o-llmstudio/assets/1069138/2cb24086-783b-4c65-b1d6-77dd63712866)

Basically, this enables you to use any drop in replacement for the open AI API. 

We are open for PRs to support Cohere API, but it's currently not a priority.

**Comment by micuentadecasa** [comment]
many thanks @pascal-pfeiffer. I will take a look to the code to see if I can do a PR.
