### ISSUE TITLE
[FEATURE] Support Jetson ORIN

### ISSUE THREAD

**Issue by micuentadecasa** [h2oai/h2o-llmstudio#417]
### 🚀 Feature

JETSON ORIN Compatibility

### Motivation

I have some Jetson ORIN devices and would like to use them to train a llama2 7b model. The docker version of LLM studio doesnt' works because of the different architecture (ARM).

It will be great if there is a Docker image for this architecture.

**Comment by pascal-pfeiffer** [comment]
Thank you for your request. 

Support for Jetson ORIN is not planned for H2O LLM Studio. We believe that these devices should rather be seen as inference devices and would advice to look for ports of inference tools such as vLLM, TGI or even transformers to that architecture. The (more complex) training could still be done on standard GPUs.

**Comment by micuentadecasa** [comment]
thanks @pascal-pfeiffer
