### ISSUE TITLE
[BUG] Default user settings are not loaded on a fresh instance

### ISSUE THREAD

**Issue by diogobragaswogo** [h2oai/h2o-llmstudio#418]
### 🐛 Bug

```
Traceback (most recent call last):

File “/workspace/./llm_studio/app_utils/handlers.py”, line 172, in handle should_list_current_experiments = await experiment_run(

File “/workspace/./llm_studio/app_utils/sections/experiment.py”, line 536, in experiment_run start_experiment(cfg=cfg, q=q, pre=pre)

File “/workspace/./llm_studio/app_utils/utils.py”, line 1728, in start_experiment p = start_process(

File “/workspace/./llm_studio/app_utils/utils.py”, line 145, in start_process p = subprocess.Popen(

File “/usr/lib/python3.10/subprocess.py”, line 971, in init self._execute_child(args, executable, preexec_fn, close_fds,

File “/usr/lib/python3.10/subprocess.py”, line 1783, in _execute_child env_list.append(k + b’=’ + os.fsencode(v))

File “/usr/lib/python3.10/os.py”, line 811, in fsencode filename = fspath(filename) # Does type-checking of filename.

TypeError: expected str, bytes or os.PathLike object, not NoneTyp
```

### To Reproduce

1. Run `sudo docker run --runtime=nvidia --shm-size=64g --init --rm -u `id -u`:`id -g` -p 10101:10101 -v `pwd`/h2o_data:/workspace/data -v `pwd`/h2o_output:/workspace/output -v `pwd`/h2o_cache:/home/llmstudio/.cache gcr.io/vorvan/h2oai/h2o-llmstudio:nightly`
2. Create an experiment with the default dataset and settings
3. The error will occur.

Additional note:

- Seems that, if the user first goes into "Settings" in "Navigation", changes a setting and then saves, the error no longer occurs.

### LLM Studio version
Nightly build version (v0.3.0-dev).

**Comment by maxjeblick** [comment]
@diogobragaswogo The issue should be resolved for the subsequent nightly, I will also double check.
