### ISSUE TITLE
[BUG] Packer - GCP: nginx misconfiguration

### ISSUE THREAD

**Issue by mmalohlava** [h2oai/h2o-llmstudio#420]
### 🐛 Bug

The default packer image for GCP launches nginx with default configuration that enables default site.
Default site simple shows a default Nginx Welcome page and ignore `conf.d/llm.conf`.

### To Reproduce
- go to GCP console -> Images
-  find image `marketplace-h2o-llm-studio-0-1-0`  https://console.cloud.google.com/compute/imagesDetail/projects/h2o-public/global/images/marketplace-h2o-llm-studio-0-1-0?project=h2o-public
- create VM
- go to public IP of the created VM

### LLM Studio version
0.1.0

**Comment by DinukaH2O** [comment]
Will look into this @mmalohlava

**Comment by DinukaH2O** [comment]
This worked after just only restarting nginx in the created VM

**Comment by DinukaH2O** [comment]
This is fixed now @mmalohlava

**Comment by pascal-pfeiffer** [comment]
Are there any actions needed or can this be closed? @DinukaH2O / @mmalohlava

**Comment by psinger** [comment]
Seems fixed, please re-open if needed.
