### ISSUE TITLE
Resume the model fine-tuning process

### ISSUE THREAD

**Issue by llmwesee** [h2oai/h2o-llmstudio#431]
I am working on a fine-tuning task using the llama2-13b model on a custom dataset. The fine-tuning process takes a long time to finish. Sometimes, I need to stop the process using the UI and resume it later from where I left off. How can I achieve this? Is there any option to resume the fine-tuning process?

**Comment by maxjeblick** [comment]
LLM Studio currently does not have an option to fully resume finetuning, as it does not store the optimizer state/dataloder state.

As a (non-perfect) workaround, you could
- Set Evaluation Epochs < 1. That will evaluate the model in between epochs and enable save best checkpoint to turn on in-between model check-pointing.
- Split up the training dataset into smaller chunks and start from model weights from a previous experiment.
