### ISSUE TITLE
[FEATURE] GPT_EVAL_MAX editable via UI

### ISSUE THREAD

**Issue by JulianGerhard21** [h2oai/h2o-llmstudio#45]
### 🚀 Feature

Soweit ich sehen konnte, gibt es derzeit kein Bedienfeld, mit dem ich die angesprochenen Environment Variable editieren kann, was dazu führt, dass das Statement WARNING: `More than 100 validation records. Safeguarding against OpenAI API costs. Setting metric to BLEU. Change GPT_EVAL_MAX to run GPT` im Log "verschluckt" wird.

### Motivation

If possible, it would probably make sense not to have to reboot the system to set this value. It might be unlikely that several experiments run in parallel - nevertheless, this could probably be avoided.

What do you think?

**Comment by pascal-pfeiffer** [comment]
Hi @JulianGerhard21 
Thank you for opening the feature request.
We can add this as a new setting on the [settings](https://github.com/h2oai/h2o-llmstudio/blob/main/app_utils/sections/settings.py) page. This way, the app will not need to be restarted when changing the value.
