### ISSUE TITLE
[BUG] 0 rows after dataset import

### ISSUE THREAD

**Issue by fatihozturkh2o** [h2oai/h2o-llmstudio#451]
### 🐛 Bug

I have a use-case where I wanted to pretrain llm models without q-a pairs necessarily. So, in my dataset, the prompt column is full of text but the answer column is empty strings.

When I try to import this dataset, I'm running into an error during the visualization part first and then see "train rows = 0" in the datasets table.

<img width="1212" alt="image" src="https://github.com/h2oai/h2o-llmstudio/assets/70659545/4fa13390-88ec-4966-b35b-1b1708259fb5">

the dataset:
[oscar_tr_ds_5000_answer.csv.zip](https://github.com/h2oai/h2o-llmstudio/files/12926817/oscar_tr_ds_5000_answer.csv.zip)

To me it looks like, LLMStudio drops every row having NaN. But I thought I needed this empty column so that I could have a successful pretraining setup. (planning to select prompt -> prompt column, answer -> empty answer column and disable every prompt-token related settings)

Wonder what you think?

**Comment by maxjeblick** [comment]
I think it makes sense to not drop columns with empty answer rows. 
Besides additional model pretraining, allowing to finetune a model to give no answer at all for certain questions should be a possibility.
