### ISSUE TITLE
[FEATURE] Experiment Logs Do Not Contain Logs from Chatting

### ISSUE THREAD

**Issue by meganjkurka** [h2oai/h2o-llmstudio#458]
The Experiment logs complete once the experiment finishes.  This means issues that occur when chatting with the finished model will not be captured in the logs.

The chat logs should be appended to the experiment logs zip file.

**Comment by maxjeblick** [comment]
We can maybe add an expandable log view to the chat tab that shows the same information as in the terminal.
Not sure if we really want to store all past chats in a persistent manner.

**Comment by pascal-pfeiffer** [comment]
Which kinds of issues are we expecting to log here?
I would not add any chats to the fine-tune training logs of LLM by default. Are you looking for an additional feature for exporting chat logs?

**Comment by pascal-pfeiffer** [comment]
Closing as not relevant for fine-tuning
