### ISSUE TITLE
[DOC] CLI documentation. Hyperlinks in Colab and Kaggle notebooks are broken. 

### ISSUE THREAD

**Issue by samvelkoch** [h2oai/h2o-llmstudio#486]
### 📃 Documentation

Documentation for CLI interface experiment fine-tuning parameters needed. 

### Motivation

All hyperlinks to documentation for CLI in Kaggle and Colab notebooks are broken :(

**Comment by maxjeblick** [comment]
Thanks for posting, will fix this.
