### ISSUE TITLE
[BUG] Errors when trying to download model.zip

### ISSUE THREAD

**Issue by Cansiano** [h2oai/h2o-llmstudio#488]
### 🐛 Bug
When trying download model.zip from experiment we get this errors.

We dont using HF api as we dont want data to be on internet.

q.app
q.user
q.client
report_error: True
q.events
q.args
report_error: True
stacktrace
Traceback (most recent call last):

File “/home/kocka/h2o-llmstudio/./llm_studio/app_utils/handlers.py”, line 312, in handle await experiment_download_model(q)

File “/home/kocka/h2o-llmstudio/./llm_studio/app_utils/sections/experiment.py”, line 1621, in experiment_download_model with set_env(HUGGINGFACE_TOKEN=q.client[“default_huggingface_api_token”]):

File “/usr/lib/python3.10/contextlib.py”, line 135, in enter return next(self.gen)

File “/home/kocka/h2o-llmstudio/./llm_studio/app_utils/utils.py”, line 2071, in set_env os.environ.update(environ)

File “/usr/lib/python3.10/_collections_abc.py”, line 999, in update self[key] = other[key]

File “/usr/lib/python3.10/os.py”, line 685, in setitem value = self.encodevalue(value)

File “/usr/lib/python3.10/os.py”, line 757, in encode raise TypeError(“str expected, not %s” % type(value).name)

TypeError: str expected, not NoneType

Error
None

Git Version
9d6e9470447ebbc96e54346365fcb168868a9033
### To Reproduce

Experiment->Download model.zip 

### LLM Studio version
9d6e9470447ebbc96e54346365fcb168868a9033

**Comment by maxjeblick** [comment]
Thanks for opening this issue! From the error logs, I think this issue has been resolved [here](https://github.com/h2oai/h2o-llmstudio/commit/e586c9727a5bac0c4f1c519c35edb5f7aa768639).

Could you update to a version that includes the commit linked above and try again?
Alternatively, you could try going to the settings path, and click on "Save settings persistently" button. This may fix `q.client[“default_huggingface_api_token”]` being `None` in https://github.com/h2oai/h2o-llmstudio/commit/9d6e9470447ebbc96e54346365fcb168868a9033.

**Comment by Cansiano** [comment]
Thanks it worked (alternative way).

**Comment by maxjeblick** [comment]
Thanks for confirming. Will close this issue, as fixed by e586c9727a5bac0c4f1c519c35edb5f7aa768639
