### ISSUE TITLE
Running a convert.py fails with vocab size mismatch

### ISSUE THREAD

**Issue by dankoz123** [h2oai/h2o-llmstudio#503]
All went fine until the beginning of this November.
When running
_$ python3 convert.py --outfile models/70B/ggml-model-f16.bin --outtype f16 ../llama/llama-2-70b-chat  --vocab-dir ../llama_

I am getting
_Traceback (most recent call last):
  File "/raid/test/LLAMA/llama.cpp/convert.py", line 1208, in <module>
    main()
  File "/raid/test/LLAMA/llama.cpp/convert.py", line 1203, in main
    OutputFile.write_all(outfile, ftype, params, model, vocab, special_vocab, concurrency = args.concurrency, endianess=endianess)
  File "/raid/test/LLAMA/llama.cpp/convert.py", line 908, in write_all
    check_vocab_size(params, vocab)
  File "/raid/test/LLAMA/llama.cpp/convert.py", line 795, in check_vocab_size
    raise Exception(msg)
Exception: Vocab size mismatch (model has -1, but ../llama/tokenizer.model has 32000)._

### To Reproduce
Follow the steps listed here: https://medium.com/@karankakwani/build-and-run-llama2-llm-locally-a3b393c1570e
The step 5 is the one that fails.

Any help much appreciated.

**Comment by psinger** [comment]
Is this related to H2O LLm Studio?
