### ISSUE TITLE
Fixing MDX-Checker issues

### ISSUE THREAD

**Issue by shaunyogeshwaran** [h2oai/h2o-llmstudio#514]
Fixing errors that come up after running the `docusaurus-mdx-checker` command after updating to Makersaurus v0.7.0

**Comment by pascal-pfeiffer** [comment]
Isn't it 0.4.0 in this the lock file?

https://github.com/h2oai/h2o-llmstudio/blob/165629ab73e51b0a95327ed145441cf82e2be471/documentation/package-lock.json#L2275-L2276

**Comment by shaunyogeshwaran** [comment]
https://github.com/h2oai/h2o-llmstudio/pull/518
