### ISSUE TITLE
Fix Critical Vulnerability - Mount rules are accidentally widened when compiled.

### ISSUE THREAD

**Issue by JeffreyCanisius04** [h2oai/h2o-llmstudio#516]
Description from scan:

In all versions of AppArmor mount rules are accidentally widened when compiled.

**Comment by pascal-pfeiffer** [comment]
Thank you for reporting a potential security issue. Could you please specify which part of the codebase exposes this?

**Comment by JeffreyCanisius04** [comment]
Im not quite sure but the package under question is this `apparmor:2.13.3-7ubuntu5.2`

**Comment by pascal-pfeiffer** [comment]
That is a vulnerability in the nvidia base docker image? 
Would an 

```
apt update
apt upgrade
```

fix this?

Otherwise, I was under the impression that the nvidia base docker images are regularly updated for critical vulnerabilities. And I would try to keep the overhead on our side on a minimum.
