### ISSUE TITLE
Fine Tune Local Dataset

### ISSUE THREAD

**Issue by beatenyou** [h2oai/h2o-llmstudio#522]
### 🚀 Feature

I'm requesting a feature to assist during LLM fine tuning. Is it possible to offer local files (.txt, .pdf, .csv, .md) for fine tuning instead of datasets? This would give users an incredible opportunity to refine their models from locally sourced files. Basically, you'd be saving the world with this request. ;)

**Comment by psinger** [comment]
Hi @beatenyou - this is already fundamentally supported, or what do you mean by "instead of datasets"?

Please take a look at the documentation for how to import a csv file:
https://docs.h2o.ai/h2o-llmstudio/guide/datasets/import-dataset

**Comment by beatenyou** [comment]
@psinger, thanks for the speedy reply. From my understanding the local upload ability is for .zip, .csv, .pq file types only and for structured data. I was looking for unstructured data types, specifically URL based, .pdf's, .docx's, and .html/.md files used for fine tuning. Is there a way to import or ingest these files types then tune?

**Comment by psinger** [comment]
No, and this is out of scope for this repository.

Please take a look at our other repository that allows you to generate input/output pairs from unstructured text:
https://github.com/h2oai/h2o-wizardlm
