### ISSUE TITLE
[BUG] Cannot Import a CSV as Dataset

### ISSUE THREAD

**Issue by lukemunn** [h2oai/h2o-llmstudio#526]
### 🐛 Bug

Import a new Dataset. 

1. Upload the dataset (it's just a local CSV). 
2. Reach the Configure screen, and select the Instruction and Output columns as 'Prompt' and 'Answer'. 
3. Hit 'Continue'. Nothing Happens. The dropdowns reset. Can't continue and the dataset doesn't show up in Existing Datasets.

The Terminal shows these lines after hitting Continue:
INFO:     127.0.0.1:48504 - "POST / HTTP/1.1" 200 OK
2023-12-05 11:28:14,032 - INFO: Initializing client True
2023-12-05 11:28:14,136 - INFO: {'settings/footer', 'home/disk_usage', 'dataset/display/footer', 'experiment/start/footer', 'dataset/import', 'home/gpu_stats', 'experiment/list', 'dataset/display/tab', 'home/compute_stats', 'dataset/import/footer', 'settings/content', 'home/experiments_stats', 'dataset/list', 'experiment/start', 'init_app', 'dataset/display/data'}

[allende_quotes.csv](https://github.com/h2oai/h2o-llmstudio/files/13553825/allende_quotes.csv)

I've attached the CSV which is all good as far as CSV Linter is concerned. 

FWIW, the same issue happens with the sample Dataset available here. https://www.kaggle.com/code/philippsinger/openassistant-conversations-dataset-oasst1/output?scriptVersionId=126228752&select=train_full.csv

I'm trying to get this working for a university project, so any help would be hugely appreciated! :-)

**Comment by maxjeblick** [comment]
Hi, @lukemunn thanks for reporting! 
Can you specify the version you are using and retry with the latest commit? There's been a short-lived issue with dataset imports, it has been introduced [here](https://github.com/h2oai/h2o-llmstudio/pull/496) and  fixed [here](https://github.com/h2oai/h2o-llmstudio/pull/500). 

I've checked the dataset attached on latest main:
![Screenshot 2023-12-05 at 10-06-53 H2O LLM Studio](https://github.com/h2oai/h2o-llmstudio/assets/24281881/cd682237-3b82-433f-8660-269ab148c6bd)
