### ISSUE TITLE
Run h2o llm stuio on runpod

### ISSUE THREAD

**Issue by andsty** [h2oai/h2o-llmstudio#535]
### 🚀 Feature
Could you also create a guide on how to deploy h2 llm studion on a gpu instance in runpod.io?

### Motivation

It would be nice to be able to deploy h20 llm studio on runpod as is a place where you can rent gpu and perform your finetuning.

**Comment by maxjeblick** [comment]
Thanks for opening the isse @andsty.

According to runpods [README](https://docs.runpod.io/docs/faq), `any Docker container available on any publicly reachable container registry` can be used as a base image. 

Our docker image is locate here: https://console.cloud.google.com/gcr/images/vorvan/global/h2oai/h2o-llmstudio


@shaunyogeshwaran Could you update the README/docs and add the link? It's currently not very visible.

**Comment by myrulezzz** [comment]
Ok thanks.I will try to create a pod and define the image as per your instructions.If i need something else i will let you know

**Comment by shaunyogeshwaran** [comment]
> Could you update the README/docs and add the link?

Sure, will get on it.

**Comment by shaunyogeshwaran** [comment]
https://github.com/h2oai/h2o-llmstudio/pull/542
