### ISSUE TITLE
[BUG] New python examples 

### ISSUE THREAD

**Issue by PGTBoos** [h2oai/h2o-llmstudio#540]

**Comment by maxjeblick** [comment]
I guess this can be closed in favour of #541 ?

**Comment by PGTBoos** [comment]
Well your closing quite quick with a solution to disable a network.. dont think that's a solution, a workaround but not usable for most people.
In simple LLM studio can work can provide a rest API, and it should react to rest API calls in form of JSON no need to use openai at all.
Redesign ?

Outlook voor Android downloaden<https://aka.ms/ghei36>
________________________________

**Comment by maxjeblick** [comment]
Hi @PGTBoos, you opened two issues (I guess by accident), with this one being empty. Your issue #541 is still open.
