### ISSUE TITLE
[BUG] New python examples (and the old too) dont work on windows?

### ISSUE THREAD

**Issue by PGTBoos** [h2oai/h2o-llmstudio#541]
### 🐛 Bug
  File "C:\Users\Peter\.pyenv\pyenv-win\versions\3.11.6\Lib\site-packages\openai\_base_client.py", line 905, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

### To Reproduce

just run on a windows system
jus for the record my firewall is disabled.
### LLM Studio version
latest official version after the verssion upgrade a few days ago

**Comment by maxjeblick** [comment]
Thanks for posting this issue. Could you provide more information on where exactly you observe this?
