### ISSUE TITLE
[FEATURE] Add KTO

### ISSUE THREAD

**Issue by maxjeblick** [h2oai/h2o-llmstudio#544]
### 🚀 Feature

Implement Kahneman-Tversky optimization, see https://github.com/ContextualAI/HALOs

### Motivation

In contrast to DPO, KTO allows for unpaired preferences (see e.g. here: https://github.com/ContextualAI/HALOs/blob/main/trainers.py#L518C1-L519C98), e.g. using a dataset with each model response rated thumbs up/thumbs down.

From https://github.com/ContextualAI/HALOs/blob/main/assets/report.pdf
![Screenshot 2023-12-19 at 15-40-44 HALOs_assets_report pdf at main · ContextualAI_HALOs](https://github.com/h2oai/h2o-llmstudio/assets/24281881/3f09abb2-11a2-496b-b6c0-ddce9f50c1ef)

Todos:
- Compare DPO/KTO models from https://github.com/ContextualAI/HALOs
- Compare different implementation possibilities. Easiest is probably to add a new column to the Dataframe ("_thumbs up/ thumbs down_") and either add a sampler or do grouping in the dataset directly (ensuring that ratio preferred vs non-preffered is fixed in each training batch).

**Comment by maxjeblick** [comment]
Things to consider:

- Evaluation when validation dataset contains non preferred data
- Handling unbalanced datasets w.r.t. preference

**Comment by psinger** [comment]
Closed in https://github.com/h2oai/h2o-llmstudio/pull/599
