### ISSUE TITLE
training with 8int leads to error

### ISSUE THREAD

**Issue by Franjcf** [h2oai/h2o-llmstudio#55]
### 🐛 Bug

int8 quantization leads to easy-to-fix error 

### To Reproduce

In the tutorial notebook, replace 'float16' for the backbone dtype to 'int8'. This leads to the following error: 
AttributeError: 'NoneType' object has no attribute 'device'

### To Fix

See: https://github.com/tloen/alpaca-lora/issues/14#issuecomment-1471263165

I fixed the code locally by changing line 598 in llm_studio/src/utils/modeling_utils.py from:

kwargs["device_map"] = {"": cfg.environment._device}  

into 

kwargs["device_map"] = {"":0}

There is probably a more elegant way to do this, as it only works with single GPU training, not distributed training.

**Comment by psinger** [comment]
Thanks a lot for reporting!

We can fix this potentially by setting the `_device` variable at
https://github.com/h2oai/h2o-llmstudio/blob/main/train.py#L470
