### ISSUE TITLE
[DOC] Explain "trust remote code" better

### ISSUE THREAD

**Issue by mashdragon** [h2oai/h2o-llmstudio#560]
### 📃 Documentation
I got this error when running a model that requires trusted code, with the trusted code setting off:
```
ValueError: Loading pansophic/rocket-3B requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.
```

But I don't know where in the model files I need to look in order to find the code that gets loaded and executed.

### Motivation

If you could please extend the documentation of the [trust remote code](https://docs.h2o.ai/h2o-llmstudio/guide/experiments/experiment-settings#trust-remote-code) section to explain how to find the code that needs to be checked, that will really help users like me figure out where to go with this information and decide whether to trust the remote code.

It might make sense to extend the ValueError message to indicate which code is attempting to be loaded.

**Comment by pascal-pfeiffer** [comment]
Thank you for raising the issue. 
`trust_remote_code` allows the use of code which is in the model repositories of huggingface but not in the transformers library. 

One example is the Falcon models.
The [config.json](https://huggingface.co/tiiuae/falcon-rw-1b/blob/main/config.json#L10) points to a file for the model description
`"AutoModel": "modeling_falcon.FalconModel",` .

This requires execution of the script in:
https://huggingface.co/tiiuae/falcon-rw-1b/blob/main/modeling_falcon.py

We can try to make it more clear or reference an explanation from huggingface if we find a good one.
