### ISSUE TITLE
[DOC] What does mixed_precision when you are already using dtype=bfloat16, int8, or int4?

### ISSUE THREAD

**Issue by Quetzalcohuatl** [h2oai/h2o-llmstudio#572]
### 📃 Documentation

Mixed precision (amp/apex) was traditionally used in the sense that you train some things in float32, and some layers in float16 where available. Now that we are often training layers in bfloat16, or even quantized to int8/int4, what does mixed_precision even do? Or does it just do nothing?

**Comment by psinger** [comment]
It will still run LoRA layers in mixed precision if you are using LoRA.

In case you are not running LoRA, selecting int8 and int4 does not work, and combination of bfloat16 and mixed precision will give a configuration error.

**Comment by Quetzalcohuatl** [comment]
> It will still run LoRA layers in mixed precision if you are using LoRA.
> 
> In case you are not running LoRA, selecting int8 and int4 does not work, and combination of bfloat16 and mixed precision will give a configuration error.

So just to understand, if I use dtype=bfloat16 and mixed_precision=True, then all non-LoRA layers are in bfloat16, and the LoRA layers would be in ... float16 as well since mixed_precision? Else they would be in float32?

**Comment by psinger** [comment]
Yeah that is correct. We could potentially also add bfloat for lora layers, but usually mixed precision is more reasonable there.
