### ISSUE TITLE
[CODE IMPROVEMENT] Add IPO 

### ISSUE THREAD

**Issue by maxjeblick** [h2oai/h2o-llmstudio#580]
### 🔧 Proposed code refactoring

Average logprob when loss is IPO, see https://github.com/huggingface/trl/pull/1265 Probably, add the same for `HingeLoss`.
We can also consider adding `DPOAverageLogProbLoss` (with a better name probably) if this turns out to be beneficial. 

### Motivation

This is the default implementation from the paper, summing seems to result in worse results and loss is length dependent.

**Comment by maxjeblick** [comment]
Fixed by [#586](https://github.com/h2oai/h2o-llmstudio/pull/586)

**Comment by AIR-hl** [comment]
@maxjeblick Hi! I have some question about average logprob in IPO loss. According to the formula in the paper, the length term used to calculate the average logprob wiil be reduced [#1677](https://github.com/huggingface/trl/issues/1677)
