### ISSUE TITLE
[FEATURE]create distributed_inference.sh with deepspeed

### ISSUE THREAD

**Issue by Quetzalcohuatl** [h2oai/h2o-llmstudio#598]
### 🚀 Feature

Allows for multigpu inference

### Motivation

Current deepspeed inference is limited to 1 gpu. Need to write my own code in order to multigpu deepspeed inference. Please add distributed inference a la prompt.py where you pass in a csv or list of pieces of text you want inference on.

**Comment by maxjeblick** [comment]
Thanks for opening this issue. Could you elaborate what issue your are facing exactly? 
Is it related/similar to https://github.com/h2oai/h2o-llmstudio/issues/482 ?

**Comment by Quetzalcohuatl** [comment]
Hi Max. Yes, looks to be a dupe. Just wanted to make predictions using a finetuned model on a new dataset. Epochs=0 is a nifty trick to do it. Ty

**Comment by psinger** [comment]
Cool - please re-open if there are any remaining issues. thx
