### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Garret012034** [h2oai/h2o-llmstudio#608]
Report Issue: H2O LLM Studio at http://172.26.78.111:10101/

q.app
q.user
q.client
home: False
report_error: True
q.events
q.args
home: False
report_error: True
stacktrace
Traceback (most recent call last):

File “/home/garret/h2o-llmstudio/./llm_studio/app_utils/handlers.py”, line 320, in handle await experiment_display(q)

File “/home/garret/h2o-llmstudio/./llm_studio/app_utils/sections/experiment.py”, line 984, in experiment_display await chat_tab(q)

File “/home/garret/h2o-llmstudio/./llm_studio/app_utils/sections/chat.py”, line 56, in chat_tab cfg, model, tokenizer = load_cfg_model_tokenizer(

File “/home/garret/h2o-llmstudio/./llm_studio/app_utils/sections/chat.py”, line 194, in load_cfg_model_tokenizer model = cfg.architecture.model_class(cfg)

File “/home/garret/h2o-llmstudio/./llm_studio/src/models/text_causal_language_modeling_model.py”, line 32, in init self.backbone, self.backbone_config = create_nlp_backbone(

File “/home/garret/h2o-llmstudio/./llm_studio/src/utils/modeling_utils.py”, line 754, in create_nlp_backbone backbone = model_class.from_pretrained(

File “/home/garret/llmstudio/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py”, line 566, in from_pretrained return model_class.from_pretrained(

File “/home/garret/llmstudio/lib/python3.10/site-packages/transformers/modeling_utils.py”, line 3694, in from_pretrained ) = cls._load_pretrained_model(

File “/home/garret/llmstudio/lib/python3.10/site-packages/transformers/modeling_utils.py”, line 4079, in _load_pretrained_model state_dict = load_state_dict(shard_file)

File “/home/garret/llmstudio/lib/python3.10/site-packages/transformers/modeling_utils.py”, line 510, in load_state_dict return safe_load_file(checkpoint_file)

File “/home/garret/llmstudio/lib/python3.10/site-packages/safetensors/torch.py”, line 310, in load_file result[k] = f.get_tensor(k)

File “/home/garret/llmstudio/lib/python3.10/site-packages/torch/utils/_device.py”, line 77, in torch_function return func(*args, **kwargs)

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 32.00 MiB. GPU 0 has a total capacty of 10.00 GiB of which 0 bytes is free. Including non-PyTorch memory, this process has 17179869184.00 GiB memory in use. Of the allocated memory 9.29 GiB is allocated by PyTorch, and 1.60 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Error
None

Git Version
015c75209e7c8b548b0de5006cdffdc4aedf99ee

**Comment by pascal-pfeiffer** [comment]
LLM Studio needs quite a bit of GPU memory to fine-tune the large language models. 
We employ state of the art techniques to reduce the amount of VRAM required for training. 
Make sure to use LoRA, gradient checkpointing, low batch size (1) and int4 quantization.
May I ask which model you were trying to fine-tune and which GPU you have? With 10 GB VRAM and the above settings, it may be possible to fine-tune a 7B model, but not larger.

**Comment by pascal-pfeiffer** [comment]
I am trying to reproduce what could be different in the chat than for fine-tune. Both use the same logic, and locally, I see the memory peaking at around 15 GB for both when loading the checkpoints. 
The batch_size is not used during inference/chat. It seems that the model exceeds max VRAM when loading the checkpoint.

**Comment by psinger** [comment]
There is a small memory leak after training, so if the weights are very tight it could oom.
Did you try restarting the whole application and then navigating to the Chat tab?

**Comment by Garret012034** [comment]
Yes, I did restart the application and restarted the machine just to be sure.

**Comment by maxjeblick** [comment]
Maybe we can init the model with empty weights before loading the checkpoint, haven't tested the workflow yet.
https://huggingface.co/docs/accelerate/v0.11.0/en/big_modeling
