### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ‘Failed to initialize NVML: Unknown Error’

### ISSUE THREAD

**Issue by jldroid19** [h2oai/h2o-llmstudio#668]
### 🐛 Bug

q.app
q.user
q.client
report_error: True
q.events
q.args
report_error: True
stacktrace
Traceback (most recent call last):

File “/workspace/./llm_studio/app_utils/handlers.py”, line 78, in handle await home(q)

File “/workspace/./llm_studio/app_utils/sections/home.py”, line 66, in home stats.append(ui.stat(label=“Current GPU load”, value=f"{get_gpu_usage():.1f}%"))

File “/workspace/./llm_studio/app_utils/utils.py”, line 1949, in get_gpu_usage all_gpus = GPUtil.getGPUs()

File “/home/llmstudio/.local/share/virtualenvs/workspace-dqq3IVyd/lib/python3.10/site-packages/GPUtil/GPUtil.py”, line 102, in getGPUs deviceIds = int(vals[i])

ValueError: invalid literal for int() with base 10: ‘Failed to initialize NVML: Unknown Error’

Error
None

Git Version
fatal: not a git repository (or any of the parent directories): .git

### To Reproduce

I'm not sure why this is happening. Hard to reproduce

### LLM Studio version
v1.4.0-dev

**Comment by psinger** [comment]
This means you have no GPUs available. Can you run `nvidia-smi` to confirm everything is fine?

**Comment by jldroid19** [comment]
![image](https://github.com/h2oai/h2o-llmstudio/assets/10508346/96c0e188-77f6-49a8-a02c-2d98a534e0e3)

![image](https://github.com/h2oai/h2o-llmstudio/assets/10508346/009e418c-d09e-49cb-97f4-75f897a9be40)


What's interesting is the environment just suddenly drops. It's like the GPU's just disappear after a few hours of training.

**Comment by psinger** [comment]
@jldroid19 did you figure the issue out?

**Comment by jldroid19** [comment]
@psinger I have not.

**Comment by psinger** [comment]
are you running this in docker?

**Comment by jldroid19** [comment]
> are you running this in docker?

Yes I am running it using docker. It's strange due to the fact, we can run a dataset on it with an expected finish of 5 days and it'll finish. We then go to start another experiment and 3 hours later the container stops. Cause it to fail the experiment. With a quick docker restart the app is back up and running, but the training that had been going is lost.

**Comment by psinger** [comment]
I stumbled upon this recently, might be related:
https://github.com/NVIDIA/nvidia-docker/issues/1469

There seems to be some issue of gpus being suddenly gone in Docker.

**Comment by psinger** [comment]
closing this for now, feel free to re-open if issue persists, but looks unrelated to LLM Studio
