### ISSUE TITLE
Compare Zero-Epoch Prediction with Fine-Tuned Prediction as well as Validation Score Comparison

### ISSUE THREAD

**Issue by meganjkurka** [h2oai/h2o-llmstudio#695]
### 🚀 Feature

In the Validation Prediction Insights, include the Zero-Epoch Response (i.e. how would the original foundation model response) as well as the BLEU (or other validation score) on the Zero-Epoch Response.  This will show the user what the original foundation model would say vs their fine-tuned model as well as the validation performance improvement from fine-tuning.

### Motivation

This will allow the user to quickly see the value of their fine-tuning exercise.

**Comment by psinger** [comment]
This can be already solved by running a separate experiment and set `epochs=0`.
One idea could be to save the output for each validation run and then display as separate columnsin the insights, but it is already pretty hard to navigate there.
