### ISSUE TITLE
[CODE IMPROVEMENT] Chat experience

### ISSUE THREAD

**Issue by psinger** [h2oai/h2o-llmstudio#7]
There are several potential things to improve experience of the chat window:

- Block the chat window if other training runs are active
- Make the actual model loading procedure a separate step
- Add sliders for inference settings / or add more helper output

**Comment by pascal-pfeiffer** [comment]
Was this fully covered in https://github.com/h2oai/h2o-llmstudio/pull/85 ?

**Comment by maxjeblick** [comment]
I'm fine with closing this issue.
