### ISSUE TITLE
Data Format section has a broken link

### ISSUE THREAD

**Issue by cemremengu** [h2oai/h2o-llmstudio#701]
[Data Format](https://github.com/h2oai/h2o-llmstudio#data-format-and-example-data) section contains a link which points to [here ](https://docs.h2o.ai/h2o-llmstudio/guide/datasets/data-connectors-format#data-format) but it is a 404 😢

**Comment by cemremengu** [comment]
FYI Link is still broken. The PR seems to make an unrelated change.

**Comment by 5675sp** [comment]
Hello @cemremengu, It should work now. Thank you so much for reporting the problem.

**Comment by cemremengu** [comment]
No problem @5675sp, thanks a lot for your work!
