### ISSUE TITLE
Thanks for this repo! (Place to discuss?)

### ISSUE THREAD

**Issue by Taytay** [h2oai/h2o-llmstudio#73]
I trained my first LLM yesterday using this, and I really appreciate you creating and open sourcing it!

On a related note, do you happen to have a Slack or Discord anywhere to discuss LLM fine tuning? I'd love to bounce some things off of other folks using this.

**Comment by psinger** [comment]
Thanks @Taytay !

We are in the progress of creating a discord to discuss. Will share very soon!

**Comment by parulnith** [comment]
@Taytay please find the link to our discord here: https://discord.gg/tyVzzrkZ
