### ISSUE TITLE
H2O LLM Studio error "Unknown exception" when running app

### ISSUE THREAD

**Issue by Quickedu** [h2oai/h2o-llmstudio#757]
I had this error just after I started one experiment. When it happened first time, it crashed the whole thing. I have restarted H2O and tried to reinstall and get GitHub directories but it does not work. Now, when I run H2O, in screen Home, View Experiment and Create experiment, I see the same screen message (I upload screenshot of it).

This is the report H2O has given:

Report Issue: H2O LLM Studio at http://192.168.1.101:10101/

q.app
script_sources: ['/_f/60417ac8-9c68-4bed-8f1c-f875e52f45ef/tmpftsu6rqn.min.js']
initialized: True
version: 1.7.0-dev
name: H2O LLM Studio
heap_mode: False
wave_utils_stack_trace_str: ### stacktrace
Traceback (most recent call last):

  File "/home/midue/h2o-llmstudio/./llm_studio/app_utils/handlers.py", line 78, in handle
    await home(q)

  File "/home/midue/h2o-llmstudio/./llm_studio/app_utils/sections/home.py", line 21, in home
    experiments = get_experiments(q)

  File "/home/midue/h2o-llmstudio/./llm_studio/app_utils/utils.py", line 1626, in get_experiments
    info = get_experiments_info(df, q)

  File "/home/midue/h2o-llmstudio/./llm_studio/app_utils/utils.py", line 1449, in get_experiments_info
    with SqliteDict(f"{row.path}/charts.db") as logs:

  File "/home/midue/llmstudio/lib/python3.10/site-packages/sqlitedict.py", line 157, in __init__
    raise RuntimeError('Error! The directory does not exist, %s' % dirname)

RuntimeError: Error! The directory does not exist, /home/midue/h2o-llmstudio/output/user/B.1.4.1.2_Casual-Modeling_h2oai-h2o-danube2-i.8b-base_Val.Size0.2_832-832-1664_bfloat16_LRate0.01_DiffLRate0.001_WarmEpoch1_Batch12_Epoch100_BLEU_AllDropout0.2_NumBeams-3_.1

q.user
q.client
app_db: <llm_studio.app_utils.db.Database object at 0x74b06815bfd0>
client_initialized: True
mode_curr: error
theme_dark: True
credential_saver: .env File
default_aws_bucket_name: bucket_name
default_azure_conn_string: 
default_azure_container: 
default_kaggle_username: 
set_max_epochs: 1000
set_max_batch_size: 256
set_max_gradient_clip: 10
set_max_lora_r: 256
set_max_lora_alpha: 256
gpu_used_for_chat: 1
default_number_of_workers: 8
default_logger: None
default_neptune_project: 
default_openai_azure: False
default_openai_api_base: https://example-endpoint.openai.azure.com
default_openai_api_deployment_id: deployment-name
default_openai_api_version: 2023-05-15
default_gpt_eval_max: 100
default_safe_serialization: True
delete_dialogs: True
chart_plot_max_points: 1000
init_interface: True
notification_bar: None
nav/active: home
home: False
report_error: True
__wave_submission_name__: report_error
q.events
q.args
report_error: True
__wave_submission_name__: report_error
stacktrace
Traceback (most recent call last):

File “/home/midue/h2o-llmstudio/./llm_studio/app_utils/handlers.py”, line 78, in handle await home(q)

File “/home/midue/h2o-llmstudio/./llm_studio/app_utils/sections/home.py”, line 21, in home experiments = get_experiments(q)

File “/home/midue/h2o-llmstudio/./llm_studio/app_utils/utils.py”, line 1626, in get_experiments info = get_experiments_info(df, q)

File “/home/midue/h2o-llmstudio/./llm_studio/app_utils/utils.py”, line 1449, in get_experiments_info with SqliteDict(f"{row.path}/charts.db") as logs:

File “/home/midue/llmstudio/lib/python3.10/site-packages/sqlitedict.py”, line 157, in init raise RuntimeError(‘Error! The directory does not exist, %s’ % dirname)

RuntimeError: Error! The directory does not exist, /home/midue/h2o-llmstudio/output/user/B.1.4.1.2_Casual-Modeling_h2oai-h2o-danube2-i.8b-base_Val.Size0.2_832-832-1664_bfloat16_LRate0.01_DiffLRate0.001_WarmEpoch1_Batch12_Epoch100_BLEU_AllDropout0.2_NumBeams-3_.1

Error
None

Git Version
6020ee4312a066a63004d7b8093653aae788a816

![chrome_2d78QKYw1D](https://github.com/h2oai/h2o-llmstudio/assets/173138884/a504c0f2-8102-44df-a4b6-e9c2966d49e6)

**Comment by Quickedu** [comment]
I just fixed it by going into the folder "../h2o-llm studio/output/user" , making a copy of one of the experiments and rename it like the experiment that H2O was telling me that was missing in logs.
:/

**Comment by psinger** [comment]
Thanks - will add a cross-check so it does not fully fail if the folder does not exist.
