### ISSUE TITLE
[DOC] Document Adding New Backbone

### ISSUE THREAD

**Issue by mtanco** [h2oai/h2o-llmstudio#765]
### 📃 Documentation

How to add a custom backbone from Hugging Face that is not in the recommended dropdown list to Step 5 of configuring parameters: https://docs.h2o.ai/h2o-llmstudio/guide/experiments/create-an-experiment

### Motivation

We mention this is supported, but we do not tell users how to do it.

**Comment by pascal-pfeiffer** [comment]
It is a dropdown that also allows for free typing. So any model from huggingface can just be copy pasted in there. I agree this isn't very intuitive for first time users. Any idea how to make it more obvious what is possible there?

**Comment by pascal-pfeiffer** [comment]
https://github.com/h2oai/h2o-llmstudio/assets/1069138/0518ad42-1801-409f-b1ad-0695695d20f1
