### ISSUE TITLE
Can't see the local saved model in the 'LLM backbone' pull down menu of 'Create Experiment'

### ISSUE THREAD

**Issue by chengchu88** [h2oai/h2o-llmstudio#769]
I have working h2ogpt running with its .cache storing multiple Llama 3 models locally.
I map the h2ogpt .cache folder to the LLM Studio container's /home/llmstudio/.cache. and hope to see the same local models as I saw in h2ogpt.
However, I still only see a 'default list' of models in the 'LLM backbone' pull down menu.
Would you kindly help or point out where i did wrong?

thank you,

**Comment by psinger** [comment]
The default list of options in the LLM backbone field will not change if you do not adjust the code for it.

But it is a free-text, you can just enter anything there. The default list is just a suggestive list.

**Comment by chengchu88** [comment]
Thank you Philipp, would you kindly point me where I can make the change?
Thanks so much!
Best
Cheng

**Comment by psinger** [comment]
You can type in the backbone field. You can just put in anything there.

**Comment by chengchu88** [comment]
Thanks Phillips, I figured it out. Appreciate your help.
