### ISSUE TITLE
Request to add setup-dev-no-flash to MakeFile

### ISSUE THREAD

**Issue by sarthak247** [h2oai/h2o-llmstudio#785]
### 🚀 Feature

As per [CONTRIBUTING.md](https://github.com/h2oai/h2o-llmstudio/blob/main/CONTRIBUTING.md), one needs to run `make setup-dev` instead of `make setup` in order to install the dev environment. However, unlike `make setup` which does have an additional option to also install the environment without `flash-attn`, `make setup-dev` doesn't have any such provision to install without `flash-attn`. I think this is something which should be investigated and added if it seems feasible enough.

### Motivation
Installing `flash-attn` can be a hassle as it depends on `cuda>=11.6`. Due to this reason, often packages come with an option to install without `flash-attn` just like llm-studio itself. However, when working with the `dev` environment, it is required to install `flash-attn` as well. This might be problematic for some as not everyone has the latest cuda version or the one `flash-attn` needs. I encountered this issue when I was myself trying to build the `dev` environment but had `cuda==11.5` which wouldn't let me proceed. Due to this, I had to install another version of `cuda` in order to just be able to setup the `dev` environment. However, I feel that this shouldn't be necessary and one should have the option to setup the `dev` environment even without `flash-attn` if they are not planning to work on any issues which need it. For example, maybe some issue with the UI, or with the documentation or some other issues which might not need `flash-attn` shouldn't be the reason someone needs to setup everything again just to get the `dev` environment working if they won't be using `flash-attn` in the first place while working on their issue. I think this should be discussed and added as an extra feature to allow to setup the dev environment without the option of installing `flash-attn`. Open to discussion if this is even needed in the first place or we can continue without this feature as well.

### POTENTIONAL FIX
After looking at the `MakeFile`, I think we would need to add another `setup-dev-no-flash` option just like `setup-no-flash`.

**Comment by pascal-pfeiffer** [comment]
Hi @sarthak247 and thank you for your interest in contributing to H2O LLM Studio.
As this is only intended for development, I don't think any extra `make` command is needed. 
Actually, H2O LLM Studio runs with cuda12.1 per f031b6e95e1347cea3d49594a1216cdb143a898b and installs the pytorch wheel for cuda12.1. On any recent setups, `flash_attn` should not be an issue to install.

> Open to discussion if this is even needed in the first place or we can continue without this feature as well.

Are you questioning if `flash_attn` should be used at all? In my opinion, yes. As of today, it is the most efficient way to run the attention for long context.

If you are running into issues installing `flash_attn`, please feel free to re-open this issue.
