### ISSUE TITLE
adding reference to trained checkpoint in GUI

### ISSUE THREAD

**Issue by Franjcf** [h2oai/h2o-llmstudio#82]
### 🔧 Proposed code refactoring

Currently, it is possible to start a fine-tuning job based on the last experiment's checkpoint by toggling an option in the GUI. However, I noticed that if I do that more than once(i.e. I create more than 1 'new' experiment from a "base" fine tuned experiment) the new experiment only loads the weights from the backbone and not the checkpoint. This also happens if I update the original data source in the GUI to another fine-tuning dataset. In these cases, I have resorted to using the CLI and hard-coding the checkpoint I want to start my training from. I think it would be a good addition to the GUI to allow us to specify the specific checkpoint instead of just having a toggle button to prevent this error. 

### Motivation

see above.

**Comment by psinger** [comment]
Thanks @Franjcf - I will look into it.

In the meantime, you can use the following setting:
![image](https://user-images.githubusercontent.com/1677826/235707971-39f44548-9e06-4531-960f-5aba888e8c5c.png)

There you can specify a link to a previous checkpoint

**Comment by Franjcf** [comment]
Hi psinger. Thanks for looking into this so quickly. Makes total sense, I was not aware of this field. I guess I was just confused because the interface changes a bit if we initialize it from a finished experiment (as opposed to a completely new experiment.) I apologize for the oversight.

**Comment by psinger** [comment]
`Pretrained Weights` also solves this.
