### ISSUE TITLE
[BUG]httpx.ReadTimeout && httpcore.ReadTimeout

### ISSUE THREAD

**Issue by caoyang-lqp** [h2oai/h2o-llmstudio#822]
### 🐛 Bug
When I run the GUI it it gets an error, everything runs fine before, and today it suddenly gets an error, does anyone know how to fix it.

![image](https://github.com/user-attachments/assets/e8663d5c-e6d1-407f-8851-a90da165bbc9)
![image](https://github.com/user-attachments/assets/8273b506-492b-4163-9730-d194a7e09947)
![image](https://github.com/user-attachments/assets/77f28654-593b-4d72-a97c-410a6fc4b827)

The contents of the strat.sh are as follows

![image](https://github.com/user-attachments/assets/c601b28f-f994-44fb-b456-2b2680500efe)

**Comment by pascal-pfeiffer** [comment]
Thank you for reporting @caoyang-lqp .
I can confirm that I also saw the error in the past, though I didn't find any way to reproduce/force it. I opened an issue at h2o-wave.
