### ISSUE TITLE
error in AutoModelForCausalLM.from_pretrained after exporting/merging LoRA llama-based model

### ISSUE THREAD

**Issue by Franjcf** [h2oai/h2o-llmstudio#83]
### 🐛 Bug

After successfully fine-tuning a llama-based model and downloading/merging the model weights through the GUI interface I get the following error whenever I want to load the model back into memory:

Some weights of the model checkpoint at models[/model](....) were not used when initializing LlamaForCausalLM: ['lm_head.0.weight']
- This IS expected if you are initializing LlamaForCausalLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LlamaForCausalLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of LlamaForCausalLM were not initialized from the model checkpoint at models[/model](...) and are newly initialized: ['lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

It seems that the saving or the LoRa-merging procedures have an issue with saving the lm_head. This is not a problem if I load the model (no LoRA merging) with the "load_cfg_model_tokenizer" function from the app_utils.sections.experiment directory. 

To be clear, fine tuning and inference works great! (thanks for that!). The problem only appears once I want to export the model.

### To Reproduce

fine tune a llama-based model (I used elinas/llama-7b-hf-transformers-4.29) and save/download. Try to load into memory afterwards using AutoModelForCausalLM.from_pretrained().

**Comment by pascal-pfeiffer** [comment]
Thank you for reporting the issue, we will look into what is causing it and how we can solve it.

As you already saw, we are casting the output of  the final layer to float32 [here](https://github.com/h2oai/h2o-llmstudio/blob/main/llm_studio/src/utils/modeling_utils.py#L445). Reverting this before merging the weights may already solve it.

```python
def prepare_model_for_lora_training(
    model, output_embedding_layer_name="lm_head", layer_norm_names=["layer_norm"]
):
    loaded_in_8bit = getattr(model, "is_loaded_in_8bit", False)

    for name, param in model.named_parameters():
        # freeze base model's layers
        param.requires_grad = False

        if loaded_in_8bit:
            # cast layer norm in fp32 for stability for 8bit models
            if param.ndim == 1 and any(
                layer_norm_name in name for layer_norm_name in layer_norm_names
            ):
                param.data = param.data.to(torch.float32)

    if hasattr(model, output_embedding_layer_name):
        output_embedding_layer = getattr(model, output_embedding_layer_name)
        input_dtype = output_embedding_layer.weight.dtype

        class CastOutputToFloat(torch.nn.Sequential):
            r"""
            Manually cast to the expected dtype of the lm_head
            as sometimes there is a final layer norm that is casted
            in fp32

            """

            def forward(self, x):
                return super().forward(x.to(input_dtype)).to(torch.float32)

        setattr(
            model,
            output_embedding_layer_name,
            CastOutputToFloat(output_embedding_layer),
        )

    return model
```

**Comment by psinger** [comment]
@Franjcf This should be now fixed in latest master!

Please give it a spin and report back if you still encounter issues. Thanks!
