### ISSUE TITLE
[BUG] Unable to run H2O LLM Studio CLI in T4 Colab

### ISSUE THREAD

**Issue by sudhir2016** [h2oai/h2o-llmstudio#846]
### 🐛 Bug

Just tried running the provided Colab. 

This step gave error !make setup > /dev/null

ERROR: Couldn't install package: {}
 Package installation failed...
/usr/lib/python3.10/subprocess.py:1072: ResourceWarning: subprocess 812 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=4 encoding='utf-8'>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=7 encoding='utf-8'>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
make: *** [Makefile:29: setup] Error 1

**Comment by pascal-pfeiffer** [comment]
I can't reproduce the error on the linked colab notebook. It runs through smoothly. Nevertheless, I'll go ahead and upgrade it to the latest release version (v1.11.1)

**Comment by pascal-pfeiffer** [comment]
Updated both with the latest release version and tested successfully on T4:

https://www.kaggle.com/code/ilu000/h2o-llm-studio-cli/
https://colab.research.google.com/drive/1soqfJjwDJwjjH-VzZYO_pUeLx5xY4N1K?usp=sharing
