### ISSUE TITLE
[DOC] Add to FAQ, facing OSError: Consistency check failed in experiment

### ISSUE THREAD

**Issue by pascal-pfeiffer** [h2oai/h2o-llmstudio#860]
### 📃 Documentation

If facing an error like this in the training

```
│ OSError: Consistency check failed: file should be of size 4999819336 but has size 14099570832 ((…)ve/main/model-00002-of-00003.safetensors). 
```

The most likely reason is network issues either on user side or on Hugging Face Hub side. In most cases, rerunning the experiment will solve it, as the download of the model weights will be re initiated. 

Let's add this to the FAQ

**Comment by sherenem** [comment]
Ack. If we have more error related advice like this, I would love to add a "Troubleshooting guide" to the LLM Studio docs.
