### ISSUE TITLE
Document H2O LLM Studio

### ISSUE THREAD

**Issue by sherenem** [h2oai/h2o-llmstudio#89]
- [x] Set up Makersaurus + templates in the repo
- [x] "What is LLM Studio?" page
- [x] Key terms 
- [x] Concepts
- [x] Set up LLM Studio + pre-reqs + installation
- [x] Supported data connectors and data format
- [x] Import a dataset (for local, upload, AWS, and Kaggle)
- [x] Configure dataset
- [x] View datasets
- [x] Merge datasets 
- [x] Dataset settings
- [x] Create an experiment
- [x] View experiments
- [x] Monitoring experiments
- [x] Compare experiments
- [x] Experiment settings
- [ ] Tutorial
- [ ] Document any details about Kaggle and Colab integration
- [ ] Example use case
- [ ] Publish and host documentation

**Comment by snehilsanyal** [comment]
Hey @sherenem is this open for contributors? I would like to explore this issue.

**Comment by sherenem** [comment]
Hi @snehilsanyal, thank you for your interest in contributing! 

After the first version of the LLM Studio docs is published, we will open it up for community contribution. Meanwhile, please do open git issues or comment on this issue about any particular documentation or tutorials you would like to see added to the docs.

**Comment by sherenem** [comment]
Resolved with https://github.com/h2oai/h2o-llmstudio/pull/156
