### ISSUE TITLE
[CODE IMPROVEMENT] Utility code for pushing to HF

### ISSUE THREAD

**Issue by psinger** [h2oai/h2o-llmstudio#95]
We currently only directly support the push to HF for the GUI via:
https://github.com/h2oai/h2o-llmstudio/blob/main/app_utils/sections/experiment.py#L1596

When using the CLI, there is no dedicated util function. We should prepare a notebook and/or dedicated util function to do the transform and push to the hub also for CLI usage.

**Comment by snehilsanyal** [comment]
Hey @psinger is this open for contribution? I would like to explore this, first-timer here. I have experience with HF Hub and downloading models using requests from the hub, locally.

**Comment by psinger** [comment]
Yes sure, but keep in mind that we have the code already ready for the GUI as per what I linked. So would just need to be ported for cli.

**Comment by snehilsanyal** [comment]
Thank you, I will take a look into the link you sent

**Comment by pascal-pfeiffer** [comment]
closed with #300
